/**
 * ExportService
 *
 * Generates authoritative GHG Protocol audit exports (CSV / XLSX / PDF).
 *
 * DB Consistency Guarantee:
 *   All emission, ef, and normalizedAmount values are read-only from the
 *   persisted inventory DB records. This service NEVER calls calculateEmission().
 *   The export is a faithful representation of immutable calculation snapshots.
 *
 * XLSX Structure (3 sheets):
 *   1. Audit Report   — 25 audit columns, numeric cells remain numbers
 *   2. Scope Summary  — Scope 1/2/3 totals + Cat 1–15 breakdown
 *   3. Metadata       — Provenance / audit certificate metadata
 *
 * PDF Structure (4 pages):
 *   Page 1  — Audit Certificate + Metadata
 *   Page 2  — Scope 1/2/3 Summary + Category Breakdown
 *   Page 3  — Facility Breakdown
 *   Page 4+ — Detailed Inventory Audit Records
 *
 * CSV Structure:
 *   Flat UTF-8 with metadata comment header + 27-column audit rows.
 *   methodologyInputsSnapshot is serialized as escaped JSON.
 */

import { Injectable } from '@nestjs/common';
import * as ExcelJS from 'exceljs';
import { InventoryEntry } from 'src/entities/inventory-entry.entity';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExportMetadata {
  organization: string;
  organizationId: number;
  reportingPeriod: string;
  reportingPeriodYear: number | undefined;
  generatedAt: string;
  generatedBy: string;
  calculationEngineVersion: '1.0.0';
  exportVersion: string;
  totalEntries: number;
  totalEmissionsTCO2e: number;
}

export interface ScopeSummary {
  scope1: number;
  scope2: number;
  scope3: number;
  scope3Categories: Record<number, number>; // key = 1..15
  grandTotal: number;
}

// ─── Scope 3 Category Labels ──────────────────────────────────────────────────

const SCOPE3_CATEGORY_LABELS: Record<number, string> = {
  1: 'Cat 1 — Purchased Goods & Services',
  2: 'Cat 2 — Capital Goods',
  3: 'Cat 3 — Fuel & Energy-Related Activities',
  4: 'Cat 4 — Upstream Transportation & Distribution',
  5: 'Cat 5 — Waste Generated in Operations',
  6: 'Cat 6 — Business Travel',
  7: 'Cat 7 — Employee Commuting',
  8: 'Cat 8 — Upstream Leased Assets',
  9: 'Cat 9 — Downstream Transportation & Distribution',
  10: 'Cat 10 — Processing of Sold Products',
  11: 'Cat 11 — Use of Sold Products',
  12: 'Cat 12 — End-of-Life Treatment of Sold Products',
  13: 'Cat 13 — Downstream Leased Assets',
  14: 'Cat 14 — Franchises',
  15: 'Cat 15 — Investments',
};

@Injectable()
export class ExportService {
  // ─── Public API ─────────────────────────────────────────────────────────────

  buildScopeSummary(entries: InventoryEntry[]): ScopeSummary {
    const summary: ScopeSummary = {
      scope1: 0,
      scope2: 0,
      scope3: 0,
      scope3Categories: {},
      grandTotal: 0,
    };

    // Initialise all 15 cat slots to 0 so zero-value categories appear explicitly
    for (let c = 1; c <= 15; c++) {
      summary.scope3Categories[c] = 0;
    }

    for (const e of entries) {
      const em = e.emission ?? 0;
      const scope = (e.scopeType ?? '').toUpperCase();

      if (scope === 'SCOPE_1') {
        summary.scope1 += em;
      } else if (scope === 'SCOPE_2') {
        summary.scope2 += em;
      } else if (scope === 'SCOPE_3') {
        summary.scope3 += em;
        const cat = e.scope3CategoryNumber;
        if (cat && cat >= 1 && cat <= 15) {
          summary.scope3Categories[cat] =
            (summary.scope3Categories[cat] ?? 0) + em;
        }
      }

      summary.grandTotal += em;
    }

    return summary;
  }

  generateCsvReport(
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): string {
    const metaHeader = [
      '# GHG PROTOCOL AUDIT REPORT',
      `# Organization,${this.escapeCsv(metadata.organization)}`,
      `# Reporting Period,${metadata.reportingPeriod}`,
      `# Calculation Engine Version,${metadata.calculationEngineVersion}`,
      `# Generated At,${metadata.generatedAt}`,
      `# Generated By,${this.escapeCsv(metadata.generatedBy)}`,
      `# Total Entries,${metadata.totalEntries}`,
      `# Total Emissions (tCO2e),${metadata.totalEmissionsTCO2e.toFixed(6)}`,
      `# Export Version,${metadata.exportVersion}`,
      '',
    ].join('\n');

    const header = [
      'ID',
      'Scope',
      'Scope3 Category No.',
      'Category',
      'Activity Name',
      'Facility',
      'Date From',
      'Date To',
      'Original Amount',
      'Original Unit',
      'Normalized Amount',
      'Normalized Unit',
      'EF (kgCO2e/unit)',
      'EF Source',
      'Factor Dataset',
      'Factor Version',
      'Factor Year',
      'Factor Basis',
      'CH4 Origin',
      'GWP Source',
      'GWP Version',
      'GWP Horizon',
      'GWP Values Snapshot',
      'Gas Breakdown Available',
      'CO2 (tCO2e)',
      'CH4 (tCO2e)',
      'N2O (tCO2e)',
      'HFC (tCO2e)',
      'PFC (tCO2e)',
      'SF6 (tCO2e)',
      'NF3 (tCO2e)',
      'Calculation Strategy',
      'Activity Type Code',
      'Radiative Forcing Type',
      'Engine Version',
      'Emission (tCO2e)',
      'Status',
      'Reporting Period',
      'Reporting Period Year',
      'Comment',
      'Methodology Inputs Snapshot',
      'Created At',
      'Updated At',
    ]
      .map(this.escapeCsv)
      .join(',');

    const rows = entries.map((e) =>
      [
        e.id,
        this.escapeCsv(e.scopeType ?? ''),
        e.scope3CategoryNumber ?? '',
        this.escapeCsv(e.category ?? ''),
        this.escapeCsv(e.name ?? ''),
        this.escapeCsv(e.facility ?? ''),
        this.escapeCsv(e.dateFrom ?? ''),
        this.escapeCsv(e.dateTo ?? ''),
        this.numericCell(e.originalAmount ?? e.amount),
        this.escapeCsv(e.originalUnit ?? e.unit ?? ''),
        this.numericCell(e.normalizedAmount ?? e.amount),
        this.escapeCsv(e.normalizedUnit ?? e.unit ?? ''),
        this.numericCell(e.ef),
        this.escapeCsv(e.efSource ?? ''),
        this.escapeCsv(e.factorDataset ?? ''),
        this.escapeCsv(e.factorVersion ?? ''),
        this.escapeCsv(e.factorYear ?? ''),
        this.escapeCsv(e.factorBasis ?? 'CO2E_TOTAL'),
        this.escapeCsv(e.ch4Origin ?? ''),
        this.escapeCsv(e.gwpSource ?? ''),
        this.escapeCsv(e.gwpVersion ?? ''),
        this.escapeCsv(e.gwpHorizon ?? '100Y'),
        this.escapeCsv(JSON.stringify(e.gwpValuesSnapshot ?? {})),
        e.gasBreakdownAvailable ? 'TRUE' : 'FALSE',
        this.numericCell(e.gasCO2),
        this.numericCell(e.gasCH4),
        this.numericCell(e.gasN2O),
        this.numericCell(e.gasHFC),
        this.numericCell(e.gasPFC),
        this.numericCell(e.gasSF6),
        this.numericCell(e.gasNF3),
        this.escapeCsv(e.calculationMethod ?? ''),
        this.escapeCsv(e.activityTypeCode ?? ''),
        this.escapeCsv(e.radiativeForcingType ?? ''),
        this.escapeCsv(e.calculationEngineVersion ?? '1.0.0'),
        this.numericCell(e.emission),
        this.escapeCsv(e.status ?? ''),
        this.escapeCsv(e.reportingPeriodName ?? ''),
        e.reportingPeriodYear ?? '',
        this.escapeCsv(e.comment ?? ''),
        this.escapeCsv(JSON.stringify(e.methodologyInputsSnapshot ?? {})),
        this.escapeCsv(e.createdAt ? new Date(e.createdAt).toISOString() : ''),
        this.escapeCsv(e.updatedAt ? new Date(e.updatedAt).toISOString() : ''),
      ].join(','),
    );

    return metaHeader + header + '\n' + rows.join('\n');
  }

  async generateXlsxReport(
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = metadata.generatedBy;
    workbook.created = new Date(metadata.generatedAt);
    workbook.properties.date1904 = false;

    this.buildAuditReportSheet(workbook, entries, metadata);
    this.buildScopeSummarySheet(workbook, entries, metadata);
    this.buildMetadataSheet(workbook, metadata);

    const arrayBuffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(arrayBuffer);
  }

  async generatePdfReport(
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): Promise<Buffer> {
    // Dynamic require to avoid jest module resolution issues with pdfkit
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    const scopeSummary = this.buildScopeSummary(entries);

    // ── Page 1: Audit Certificate ──────────────────────────────────────────
    this.pdfAuditCertificate(doc, metadata, scopeSummary);

    // ── Page 2: Scope Summary ──────────────────────────────────────────────
    doc.addPage();
    this.pdfScopeSummary(doc, scopeSummary, metadata);

    // ── Page 3: Facility Breakdown ─────────────────────────────────────────
    doc.addPage();
    this.pdfFacilityBreakdown(doc, entries, metadata);

    // ── Page 4+: Detailed Inventory Audit Records ──────────────────────────
    doc.addPage();
    this.pdfInventoryDetail(doc, entries, metadata);

    doc.end();

    return new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  // ─── XLSX Sheet Builders ─────────────────────────────────────────────────

  private buildAuditReportSheet(
    workbook: ExcelJS.Workbook,
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): void {
    const sheet = workbook.addWorksheet('Audit Report');

    // Header styling
    const HEADER_FILL: ExcelJS.Fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E3A5F' },
    };
    const HEADER_FONT: Partial<ExcelJS.Font> = {
      bold: true,
      color: { argb: 'FFFFFFFF' },
      size: 9,
    };
    const NUMERIC_FORMAT = '0.000000'; // 6 decimal places

    const COLUMNS: Array<{
      header: string;
      key: string;
      width: number;
      numericFormat?: string;
    }> = [
      { header: 'ID', key: 'id', width: 8 },
      { header: 'Scope', key: 'scopeType', width: 12 },
      { header: 'Cat No.', key: 'scope3CategoryNumber', width: 8 },
      { header: 'Category', key: 'category', width: 28 },
      { header: 'Activity Name', key: 'name', width: 32 },
      { header: 'Facility', key: 'facility', width: 20 },
      { header: 'Date From', key: 'dateFrom', width: 12 },
      { header: 'Date To', key: 'dateTo', width: 12 },
      {
        header: 'Orig. Amount',
        key: 'originalAmount',
        width: 14,
        numericFormat: NUMERIC_FORMAT,
      },
      { header: 'Orig. Unit', key: 'originalUnit', width: 12 },
      {
        header: 'Norm. Amount',
        key: 'normalizedAmount',
        width: 14,
        numericFormat: NUMERIC_FORMAT,
      },
      { header: 'Norm. Unit', key: 'normalizedUnit', width: 12 },
      {
        header: 'EF (kgCO2e/unit)',
        key: 'ef',
        width: 16,
        numericFormat: NUMERIC_FORMAT,
      },
      { header: 'EF Source', key: 'efSource', width: 16 },
      { header: 'Factor Dataset', key: 'factorDataset', width: 16 },
      { header: 'Factor Version', key: 'factorVersion', width: 14 },
      { header: 'Factor Year', key: 'factorYear', width: 12 },
      { header: 'Factor Basis', key: 'factorBasis', width: 16 },
      { header: 'CH4 Origin', key: 'ch4Origin', width: 12 },
      { header: 'GWP Source', key: 'gwpSource', width: 14 },
      { header: 'Strategy', key: 'calculationMethod', width: 28 },
      { header: 'Engine Version', key: 'calculationEngineVersion', width: 14 },
      {
        header: 'Emission (tCO2e)',
        key: 'emission',
        width: 16,
        numericFormat: NUMERIC_FORMAT,
      },
      { header: 'Status', key: 'status', width: 12 },
      { header: 'Reporting Period', key: 'reportingPeriodName', width: 18 },
    ];

    sheet.columns = COLUMNS.map((c) => ({
      header: c.header,
      key: c.key,
      width: c.width,
    }));

    // Style header row
    const headerRow = sheet.getRow(1);
    headerRow.eachCell((cell) => {
      cell.fill = HEADER_FILL;
      cell.font = HEADER_FONT;
      cell.alignment = {
        vertical: 'middle',
        horizontal: 'center',
        wrapText: true,
      };
    });
    headerRow.height = 28;
    sheet.views = [{ state: 'frozen', ySplit: 1 }];

    // Data rows — numeric fields stored as numbers (not strings)
    entries.forEach((e) => {
      const row = sheet.addRow({
        id: e.id,
        scopeType: e.scopeType ?? '',
        scope3CategoryNumber: e.scope3CategoryNumber ?? null,
        category: e.category ?? '',
        name: e.name ?? '',
        facility: e.facility ?? '',
        dateFrom: e.dateFrom ?? '',
        dateTo: e.dateTo ?? '',
        originalAmount: e.originalAmount ?? e.amount ?? null,
        originalUnit: e.originalUnit ?? e.unit ?? '',
        normalizedAmount: e.normalizedAmount ?? e.amount ?? null,
        normalizedUnit: e.normalizedUnit ?? e.unit ?? '',
        ef: e.ef ?? null,
        efSource: e.efSource ?? '',
        factorDataset: e.factorDataset ?? '',
        factorVersion: e.factorVersion ?? '',
        factorYear: e.factorYear ?? '',
        factorBasis: e.factorBasis ?? 'CO2E_TOTAL',
        ch4Origin: e.ch4Origin ?? '',
        gwpSource: e.gwpSource ?? '',
        calculationMethod: e.calculationMethod ?? '',
        calculationEngineVersion: e.calculationEngineVersion ?? '1.0.0',
        emission: e.emission ?? null,
        status: e.status ?? '',
        reportingPeriodName: e.reportingPeriodName ?? '',
      });

      // Apply numeric format to numeric cells
      COLUMNS.forEach((col, idx) => {
        if (col.numericFormat) {
          const cell = row.getCell(idx + 1);
          if (cell.value !== null && cell.value !== undefined) {
            cell.numFmt = col.numericFormat;
          }
        }
      });

      // Zebra stripe
      if (entries.indexOf(e) % 2 === 1) {
        row.eachCell((cell) => {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFF5F7FA' },
          };
        });
      }
    });

    // Auto-filter
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: COLUMNS.length },
    };
  }

  private buildScopeSummarySheet(
    workbook: ExcelJS.Workbook,
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): void {
    const sheet = workbook.addWorksheet('Scope Summary');
    const scopeSummary = this.buildScopeSummary(entries);

    const TITLE_FONT: Partial<ExcelJS.Font> = { bold: true, size: 12 };
    const SECTION_FILL: ExcelJS.Fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E3A5F' },
    };
    const SECTION_FONT: Partial<ExcelJS.Font> = {
      bold: true,
      color: { argb: 'FFFFFFFF' },
      size: 10,
    };
    const NUMERIC_FORMAT = '0.000000';

    sheet.getColumn(1).width = 42;
    sheet.getColumn(2).width = 20;

    // Title
    sheet.mergeCells('A1:B1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = `GHG Scope Summary — ${metadata.reportingPeriod}`;
    titleCell.font = TITLE_FONT;
    titleCell.alignment = { horizontal: 'center' };

    const addSectionHeader = (label: string, row: number) => {
      sheet.mergeCells(`A${row}:B${row}`);
      const cell = sheet.getCell(`A${row}`);
      cell.value = label;
      cell.font = SECTION_FONT;
      cell.fill = SECTION_FILL;
    };

    const addDataRow = (
      label: string,
      value: number,
      row: number,
      indent = false,
    ) => {
      const labelCell = sheet.getCell(`A${row}`);
      const valueCell = sheet.getCell(`B${row}`);
      labelCell.value = indent ? `    ${label}` : label;
      labelCell.font = { bold: !indent };
      valueCell.value = value;
      valueCell.numFmt = NUMERIC_FORMAT;
      valueCell.alignment = { horizontal: 'right' };
    };

    let r = 2;

    // ── Scope 1 ──
    addSectionHeader('Scope 1 — Direct Emissions', r++);
    addDataRow('Scope 1 Total (tCO₂e)', scopeSummary.scope1, r++);

    // ── Scope 2 ──
    r++;
    addSectionHeader('Scope 2 — Indirect (Energy)', r++);
    addDataRow('Scope 2 Total (tCO₂e)', scopeSummary.scope2, r++);

    // ── Scope 3 ──
    r++;
    addSectionHeader('Scope 3 — Other Indirect Emissions', r++);
    addDataRow('Scope 3 Total (tCO₂e)', scopeSummary.scope3, r++);
    r++;
    addSectionHeader('Scope 3 Category Breakdown', r++);

    for (let cat = 1; cat <= 15; cat++) {
      const label = SCOPE3_CATEGORY_LABELS[cat] ?? `Cat ${cat}`;
      addDataRow(label, scopeSummary.scope3Categories[cat] ?? 0, r++, true);
    }

    // ── Grand Total ──
    r++;
    const grandTotalLabelCell = sheet.getCell(`A${r}`);
    const grandTotalValueCell = sheet.getCell(`B${r}`);
    grandTotalLabelCell.value = 'Grand Total — Scope 1 + 2 + 3 (tCO₂e)';
    grandTotalLabelCell.font = { bold: true, size: 11 };
    grandTotalValueCell.value = scopeSummary.grandTotal;
    grandTotalValueCell.numFmt = NUMERIC_FORMAT;
    grandTotalValueCell.font = { bold: true, size: 11 };
    grandTotalValueCell.alignment = { horizontal: 'right' };
    grandTotalLabelCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFEF3C7' },
    };
    grandTotalValueCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFEF3C7' },
    };
  }

  private buildMetadataSheet(
    workbook: ExcelJS.Workbook,
    metadata: ExportMetadata,
  ): void {
    const sheet = workbook.addWorksheet('Metadata');
    sheet.getColumn(1).width = 32;
    sheet.getColumn(2).width = 48;

    const HEADER_FILL: ExcelJS.Fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E3A5F' },
    };
    const HEADER_FONT: Partial<ExcelJS.Font> = {
      bold: true,
      color: { argb: 'FFFFFFFF' },
      size: 11,
    };

    sheet.mergeCells('A1:B1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = 'GHG Protocol Audit Report — Provenance Metadata';
    titleCell.font = HEADER_FONT;
    titleCell.fill = HEADER_FILL;
    titleCell.alignment = { horizontal: 'center' };

    const rows: Array<[string, string | number]> = [
      ['Organization', metadata.organization],
      ['Organization ID', metadata.organizationId],
      ['Reporting Period', metadata.reportingPeriod],
      ['Reporting Period Year', metadata.reportingPeriodYear ?? 'All Periods'],
      ['Calculation Engine Version', metadata.calculationEngineVersion],
      ['Export Version', metadata.exportVersion],
      ['Generated At', metadata.generatedAt],
      ['Generated By', metadata.generatedBy],
      ['Total Entries', metadata.totalEntries],
      ['Total Emissions (tCO₂e)', metadata.totalEmissionsTCO2e],
      ['GWP Standard', 'IPCC AR6 (Aug 2024)'],
      ['Fossil CH₄ GWP100', 29.8],
      ['Non-Fossil CH₄ GWP100', 27.0],
      ['N₂O GWP100', 273],
      ['SF₆ GWP100', 24300],
      ['NF₃ GWP100', 17400],
      ['CO₂ GWP100', 1],
    ];

    rows.forEach(([label, value], i) => {
      const labelCell = sheet.getCell(`A${i + 2}`);
      const valueCell = sheet.getCell(`B${i + 2}`);
      labelCell.value = label;
      labelCell.font = { bold: true };
      valueCell.value = value;
      if (i % 2 === 0) {
        const fill: ExcelJS.Fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF5F7FA' },
        };
        labelCell.fill = fill;
        valueCell.fill = fill;
      }
    });
  }

  // ─── PDF Page Builders ───────────────────────────────────────────────────

  private pdfAuditCertificate(
    doc: any,
    metadata: ExportMetadata,
    scopeSummary: ScopeSummary,
  ): void {
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text('GHG Protocol Audit Report Certificate', { align: 'center' });
    doc.moveDown(0.5);
    doc
      .fontSize(11)
      .font('Helvetica')
      .text('─'.repeat(80), { align: 'center' });
    doc.moveDown();

    const fields: Array<[string, string | number]> = [
      ['Organization', metadata.organization],
      ['Reporting Period', metadata.reportingPeriod],
      ['Calculation Engine Version', metadata.calculationEngineVersion],
      [
        'GWP Standard',
        'IPCC AR6 (Aug 2024) — Fossil CH₄=29.8, Non-Fossil CH₄=27.0, N₂O=273',
      ],
      ['Generated At', metadata.generatedAt],
      ['Generated By', metadata.generatedBy],
      ['Export Version', metadata.exportVersion],
      ['Total Activity Entries', metadata.totalEntries],
      ['Total Footprint (tCO₂e)', metadata.totalEmissionsTCO2e.toFixed(6)],
    ];

    fields.forEach(([label, value]) => {
      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(String(value));
    });

    doc.moveDown();
    doc.fontSize(10).text('─'.repeat(80));
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica-Bold').text('Scope Totals:');
    doc
      .font('Helvetica')
      .text(`  Scope 1: ${scopeSummary.scope1.toFixed(6)} tCO₂e`)
      .text(`  Scope 2: ${scopeSummary.scope2.toFixed(6)} tCO₂e`)
      .text(`  Scope 3: ${scopeSummary.scope3.toFixed(6)} tCO₂e`)
      .text(`  Grand Total: ${scopeSummary.grandTotal.toFixed(6)} tCO₂e`, {
        underline: false,
      });
    doc.moveDown();
    doc
      .fontSize(8)
      .fillColor('grey')
      .text(
        'This report was generated by the authoritative GHG calculation engine. All emission values are immutable snapshots from the calculation engine v1.0.0 and must not be recomputed downstream.',
        { align: 'justify' },
      );
    doc.fillColor('black');
  }

  private pdfScopeSummary(
    doc: any,
    scopeSummary: ScopeSummary,
    metadata: ExportMetadata,
  ): void {
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(`Scope 1 / 2 / 3 Summary — ${metadata.reportingPeriod}`);
    doc.moveDown(0.5);

    doc.fontSize(11).font('Helvetica-Bold').text('Scope 1 — Direct Emissions');
    doc
      .font('Helvetica')
      .text(`Total: ${scopeSummary.scope1.toFixed(6)} tCO₂e`);
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').text('Scope 2 — Indirect (Energy)');
    doc
      .font('Helvetica')
      .text(`Total: ${scopeSummary.scope2.toFixed(6)} tCO₂e`);
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').text('Scope 3 — Other Indirect Emissions');
    doc
      .font('Helvetica')
      .text(`Total: ${scopeSummary.scope3.toFixed(6)} tCO₂e`);
    doc.moveDown(0.3);

    doc.font('Helvetica-Bold').fontSize(10).text('Category Breakdown:');
    for (let cat = 1; cat <= 15; cat++) {
      const label = SCOPE3_CATEGORY_LABELS[cat] ?? `Cat ${cat}`;
      const value = scopeSummary.scope3Categories[cat] ?? 0;
      doc
        .font('Helvetica')
        .fontSize(9)
        .text(`  ${label}: ${value.toFixed(6)} tCO₂e`);
    }

    doc.moveDown();
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .text(`Grand Total: ${scopeSummary.grandTotal.toFixed(6)} tCO₂e`);
  }

  private pdfFacilityBreakdown(
    doc: any,
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): void {
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(`Facility Breakdown — ${metadata.reportingPeriod}`);
    doc.moveDown(0.5);

    const facilityMap: Record<string, number> = {};
    for (const e of entries) {
      const fac = e.facility || 'Unassigned';
      facilityMap[fac] = (facilityMap[fac] ?? 0) + (e.emission ?? 0);
    }

    const sorted = Object.entries(facilityMap).sort(([, a], [, b]) => b - a);

    if (sorted.length === 0) {
      doc.font('Helvetica').text('No facility data available.');
      return;
    }

    sorted.forEach(([facility, emission]) => {
      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .text(facility, { continued: true });
      doc.font('Helvetica').text(`: ${emission.toFixed(6)} tCO₂e`);
    });

    doc.moveDown();
    const total = sorted.reduce((acc, [, v]) => acc + v, 0);
    doc.font('Helvetica-Bold').text(`Total: ${total.toFixed(6)} tCO₂e`);
  }

  private pdfInventoryDetail(
    doc: any,
    entries: InventoryEntry[],
    metadata: ExportMetadata,
  ): void {
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(`Detailed Inventory Audit Records — ${metadata.reportingPeriod}`);
    doc.moveDown(0.5);
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('grey')
      .text(
        'All values are immutable snapshots from calculation engine v1.0.0. Do not recompute.',
      );
    doc.fillColor('black').moveDown(0.5);

    entries.forEach((e, idx) => {
      if (idx > 0 && idx % 20 === 0) {
        doc.addPage();
        doc
          .fontSize(10)
          .font('Helvetica-Bold')
          .text(
            `Inventory (continued) — Page records ${idx + 1}–${Math.min(idx + 20, entries.length)}`,
          );
        doc.moveDown(0.3);
      }

      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .text(
          `${idx + 1}. [${e.scopeType ?? 'N/A'}] ${e.category ?? ''} — ${e.name ?? ''}`,
          { continued: true },
        );
      doc.font('Helvetica').text(`: ${(e.emission ?? 0).toFixed(6)} tCO₂e`);
      doc
        .fontSize(8)
        .fillColor('grey')
        .text(
          `   Strategy: ${e.calculationMethod ?? 'N/A'} | EF: ${e.ef} kgCO₂e/${e.unit ?? 'unit'} | Basis: ${e.factorBasis ?? 'CO2E_TOTAL'} | Engine: v${e.calculationEngineVersion ?? '1.0.0'}`,
        );
      doc.fillColor('black');
    });
  }

  // ─── Utilities ────────────────────────────────────────────────────────────

  private escapeCsv(value: string): string {
    if (value === null || value === undefined) return '""';
    const str = String(value);
    // RFC 4180 — wrap in quotes, escape internal quotes by doubling
    return `"${str.replace(/"/g, '""')}"`;
  }

  private numericCell(value: number | null | undefined): number | string {
    if (value === null || value === undefined) return '';
    return value;
  }
}
