export enum ActivityCode {
  SC = 'SC',
  MC = 'MC',
  FE = 'FE',
  DPE = 'DPE',
  PE = 'PE',
  PHC = 'PHC',
  PGS = 'PGS',
  CG = 'CG',
  FERA = 'FERA',
  UTD = 'UTD',
  WGB = 'WGB',
  BT = 'BT',
  EC = 'EC',
  DTD = 'DTD',
  PSP = 'PSP',
  USP = 'USP',
  EOL = 'EOL',
  FR = 'FR',
  INV = 'INV',
}

export const ACTIVITY_NAME_MAP: Record<
  ActivityCode,
  { name: string; scope: '1' | '2' | '3' }
> = {
  [ActivityCode.SC]: { name: 'Stationary Combustion', scope: '1' },
  [ActivityCode.MC]: { name: 'Mobile Combustion', scope: '1' },
  [ActivityCode.FE]: { name: 'Fugitive Emissions', scope: '1' },
  [ActivityCode.DPE]: { name: 'Process Emissions', scope: '1' },
  [ActivityCode.PE]: { name: 'Purchased Electricity', scope: '2' },
  [ActivityCode.PHC]: { name: 'Purchased Heating & Steam', scope: '2' },
  [ActivityCode.PGS]: { name: 'Purchased Goods and Services', scope: '3' },
  [ActivityCode.CG]: { name: 'Capital Goods', scope: '3' },
  [ActivityCode.FERA]: {
    name: 'Energy and Fuel Related Activities',
    scope: '3',
  },
  [ActivityCode.UTD]: { name: 'Upstream Transportation', scope: '3' },
  [ActivityCode.WGB]: { name: 'Waste Generated in Operations', scope: '3' },
  [ActivityCode.BT]: { name: 'Business Travel', scope: '3' },
  [ActivityCode.EC]: { name: 'Employee Commuting', scope: '3' },
  [ActivityCode.DTD]: { name: 'Downstream Transportation', scope: '3' },
  [ActivityCode.PSP]: { name: 'Processing of Sold Products', scope: '3' },
  [ActivityCode.USP]: { name: 'Use of Sold Products', scope: '3' },
  [ActivityCode.EOL]: { name: 'EOL Treatment of Sold Products', scope: '3' },
  [ActivityCode.FR]: { name: 'Franchise', scope: '3' },
  [ActivityCode.INV]: { name: 'Investments', scope: '3' },
};
