export enum MrvStatusEnum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUDITED = 'AUDITED',
  LOCKED = 'LOCKED',
}

export enum MrvAuditEventTypeEnum {
  CREATED = 'CREATED',
  STATUS_CHANGE = 'STATUS_CHANGE',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  CALCULATION_RERUN = 'CALCULATION_RERUN',
  REJECTED = 'REJECTED',
  LOCK_APPLIED = 'LOCK_APPLIED',
  UNLOCK_ATTEMPT_DENIED = 'UNLOCK_ATTEMPT_DENIED',
}
