import { MasterFormula } from 'src/entities/master-formula.entity';
import { MasterEmissionFactor } from 'src/entities/master-emission-factor.entity';

export const SEED_MASTER_FORMULAS: Partial<MasterFormula>[] = [
  {
    name: 'Distance-Based Emission Formula',
    methodCode: 'DISTANCE_BASED',
    formula: '(amount * ef) / 1000',
    variables: ['amount', 'ef'],
    description: 'Calculates passenger-km or vehicle-km transport emissions: (pkm × factor) / 1000',
    outputUnit: 'tCO2e',
    gasRatios: {
      CO2: 0.9844,
      CH4: 0.0015,
      N2O: 0.0141,
      HFC: 0,
      PFC: 0,
      SF6: 0,
      NF3: 0,
    },
    isActive: true,
  },
  {
    name: 'Fuel-Based Combustion Formula',
    methodCode: 'FUEL_BASED',
    formula: '(amount * ef) / 1000',
    variables: ['amount', 'ef'],
    description: 'Standard fuel combustion conversion: (fuel_amount × factor) / 1000. Gas breakdown driven directly by authoritative component factors.',
    outputUnit: 'tCO2e',
    gasRatios: null, // No fabricated ratios; component breakdown is populated only from authoritative published factors
    isActive: true,
  },
  {
    name: 'Distance-Weight Freight Formula',
    methodCode: 'DISTANCE_WEIGHT',
    formula: '(distance * weight * factor) / 1000',
    variables: ['distance', 'weight', 'factor'],
    description: 'Freight haul transport emissions: (tonne × km × factor) / 1000',
    outputUnit: 'tCO2e',
    gasRatios: {
      CO2: 0.9844,
      CH4: 0.0015,
      N2O: 0.0141,
      HFC: 0,
      PFC: 0,
      SF6: 0,
      NF3: 0,
    },
    isActive: true,
  },
  {
    name: 'Spend-Based EEIO Formula',
    methodCode: 'SPEND_EEIO',
    formula: '(spend * eeio_factor) / 1000',
    variables: ['spend', 'eeio_factor'],
    description: 'Economic input-output model: (spend_amount × eeio_factor) / 1000',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
  {
    name: 'Refrigerant Leakage Rate Formula',
    methodCode: 'LEAKAGE_RATE',
    formula: '(amount * (leakage / 100) * GWP) / 1000',
    variables: ['amount', 'leakage', 'GWP'],
    description: 'Fugitive gas leakage: (capacity × leakage_rate × GWP) / 1000. Chemical family classification determines species allocation.',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
  {
    name: 'Energy-Based Consumption Formula',
    methodCode: 'ENERGY_BASED',
    formula: '(amount * ef) / 1000',
    variables: ['amount', 'ef'],
    description: 'Purchased electricity, steam, heating and cooling: (energy_amount × factor) / 1000',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
  {
    name: 'Mass-Based Material Balance Formula',
    methodCode: 'MASS_BASED',
    formula: '(amount * ef) / 1000',
    variables: ['amount', 'ef'],
    description: 'Material mass balance calculation: (amount_kg × ef_kgCO2e_per_kg) / 1000',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
  {
    name: 'Financed Proportional Equity Formula',
    methodCode: 'INVESTMENT_EQUITY',
    formula: '(investeeScope1 + investeeScope2) * (equityShare / 100)',
    variables: ['investeeScope1', 'investeeScope2', 'equityShare'],
    description: 'Financed emissions proportional equity share: (scope1 + scope2) × (equity% / 100)',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
  {
    name: 'Financed Sector Average Data Formula',
    methodCode: 'INVESTMENT_AVERAGE_DATA',
    formula: '((investeeRevenue * factor) / 1000) * (equityShare / 100)',
    variables: ['investeeRevenue', 'factor', 'equityShare'],
    description: 'Financed emissions economic average: (revenue × factor / 1000) × (equity% / 100)',
    outputUnit: 'tCO2e',
    gasRatios: null,
    isActive: true,
  },
];

export const SEED_MASTER_EMISSION_FACTORS: Partial<MasterEmissionFactor>[] = [
  // ─── Business Travel: Air (DEFRA 2024, POC vertical slice) ─────────────────
  {
    factorVersionId: 1, // DEFRA 2024
    unitId: 1, // pas.km or km
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'short-haul economy',
    geography: 'GB',
    withRF: false,
    factor: 0.151,
    co2Factor: 0.1486,
    ch4Factor: 0.0002,
    n2oFactor: 0.0022,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Business travel - air / Table: Flights short-haul economy',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Aviation Transport',
    blendComposition: null,
    description: 'DEFRA 2024 - Air Travel - Short-haul flights (Economy class) without Radiative Forcing',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'long-haul economy',
    geography: 'GB',
    withRF: false,
    factor: 0.195,
    co2Factor: 0.192,
    ch4Factor: 0.0003,
    n2oFactor: 0.0027,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Business travel - air / Table: Flights long-haul economy',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Aviation Transport',
    blendComposition: null,
    description: 'DEFRA 2024 - Air Travel - Long-haul flights (Economy class) without Radiative Forcing',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'short-haul economy',
    geography: 'GB',
    withRF: true,
    factor: 0.255,
    co2Factor: 0.251,
    ch4Factor: 0.0004,
    n2oFactor: 0.0036,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Business travel - air with RF / Table: Flights short-haul economy',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Aviation Transport (RF Uplift)',
    blendComposition: null,
    description: 'DEFRA 2024 - Air Travel - Short-haul flights (Economy class) with Radiative Forcing',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'long-haul economy',
    geography: 'GB',
    withRF: true,
    factor: 0.352,
    co2Factor: 0.346,
    ch4Factor: 0.0005,
    n2oFactor: 0.0055,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Business travel - air with RF / Table: Flights long-haul economy',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Aviation Transport (RF Uplift)',
    blendComposition: null,
    description: 'DEFRA 2024 - Air Travel - Long-haul flights (Economy class) with Radiative Forcing',
    isActive: true,
  },

  // ─── Business Travel: Rail (DEFRA 2024) ───────────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'national rail',
    geography: 'GB',
    withRF: false,
    factor: 0.035,
    co2Factor: 0.0345,
    ch4Factor: 0.0001,
    n2oFactor: 0.0004,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Passenger land transport / Table: National rail',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Rail Transport',
    blendComposition: null,
    description: 'DEFRA 2024 - Rail Travel - National Rail - kgCO2e/pkm',
    isActive: true,
  },

  // ─── Scope 1: Stationary Combustion (DEFRA 2024) ──────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'FUEL_BASED',
    activitySubType: 'natural gas',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1.9422,
    co2Factor: 1.9360,
    ch4Factor: 0.0049,
    n2oFactor: 0.0013,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Fuels / Table: Natural Gas (100% GCV)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Natural Gas / Hydrocarbons',
    blendComposition: null,
    description: 'DEFRA 2024 - Natural Gas - 100% GCV - kgCO2e/sm3 [Full Set / Fuels]',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'FUEL_BASED',
    activitySubType: 'diesel',
    geography: 'GLOBAL',
    withRF: false,
    factor: 2.68725,
    co2Factor: 2.6790,
    ch4Factor: 0.0068,
    n2oFactor: 0.00145,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Fuels / Table: Gas Oil',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Mineral Diesel Fuel',
    blendComposition: null,
    description: 'DEFRA 2024 - Gas Oil / Diesel (100% mineral) - kgCO2e/L [Full Set / Fuels]',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'FUEL_BASED',
    activitySubType: 'petrol',
    geography: 'GLOBAL',
    withRF: false,
    factor: 2.3144,
    co2Factor: 2.3070,
    ch4Factor: 0.0059,
    n2oFactor: 0.0015,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Fuels / Table: Petrol (100% mineral petrol)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Motor Gasoline',
    blendComposition: null,
    description: 'DEFRA 2024 - Petrol (100% mineral petrol) - kgCO2e/L [Full Set / Fuels]',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'FUEL_BASED',
    activitySubType: 'lpg',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1.55709,
    co2Factor: 1.5510,
    ch4Factor: 0.0042,
    n2oFactor: 0.00189,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Fuels / Table: LPG',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Liquefied Petroleum Gas',
    blendComposition: null,
    description: 'DEFRA 2024 - LPG (Liquefied Petroleum Gas) - kgCO2e/L [Full Set / Fuels]',
    isActive: true,
  },

  // ─── Scope 1: Mobile Combustion (DEFRA 2024) ──────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'Passenger Car - Diesel - Average',
    geography: 'GB',
    withRF: false,
    factor: 0.16844,
    co2Factor: 0.1668,
    ch4Factor: 0.00014,
    n2oFactor: 0.0015,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Passenger vehicles / Table: Cars (by size) / Diesel / Average',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Transport Combustion',
    blendComposition: null,
    description: 'DEFRA 2024 - Passenger Car - Diesel - Average - kgCO2e/km [Passenger vehicles]',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'Passenger Car - Petrol - Average',
    geography: 'GB',
    withRF: false,
    factor: 0.17048,
    co2Factor: 0.1689,
    ch4Factor: 0.00018,
    n2oFactor: 0.0014,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Passenger vehicles / Table: Cars (by size) / Petrol / Average',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Transport Combustion',
    blendComposition: null,
    description: 'DEFRA 2024 - Passenger Car - Petrol - Average - kgCO2e/km [Passenger vehicles]',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'Van - Class III Diesel (>1.74t to 3.5t)',
    geography: 'GB',
    withRF: false,
    factor: 0.2458,
    co2Factor: 0.2435,
    ch4Factor: 0.0002,
    n2oFactor: 0.0021,
    gwpBasis: 'AR6',
    sourcePublisher: 'UK DESNZ / DEFRA',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Vans / Table: Class III (>1.74t to 3.5t)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Transport Combustion',
    blendComposition: null,
    description: 'DEFRA 2024 - Class III Diesel Van (>1.74t to 3.5t) - kgCO2e/km [Vans]',
    isActive: true,
  },

  // ─── Scope 1: Fugitive Emissions (IPCC / DEFRA 2024) ──────────────────────
  {
    factorVersionId: 2, // IPCC / DEFRA
    unitId: 1,
    calculationMethod: 'LEAKAGE_RATE',
    activitySubType: 'r-410a',
    geography: 'GLOBAL',
    withRF: false,
    factor: 2088.0,
    co2Factor: 0,
    ch4Factor: 0,
    n2oFactor: 0,
    hfcFactor: 2088.0,
    gwpBasis: 'AR4/DEFRA 2024 blend',
    sourcePublisher: 'UK DESNZ / DEFRA & IPCC',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024 / IPCC AR4 blend model',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Refrigerant & other / Table: Refrigerant blends / R-410A',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'HFC Blend',
    blendComposition: '50% HFC-32 (difluoromethane) / 50% HFC-125 (pentafluoroethane). Blend GWP = 0.5*675 + 0.5*3500 = 2087.5 ≈ 2088',
    description: 'DEFRA 2024 / IPCC - Refrigerant R-410A (Zeotropic HFC blend: 50% HFC-32 / 50% HFC-125, GWP-100 = 2088)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'LEAKAGE_RATE',
    activitySubType: 'r-134a',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1430.0,
    co2Factor: 0,
    ch4Factor: 0,
    n2oFactor: 0,
    hfcFactor: 1430.0,
    gwpBasis: 'AR4/DEFRA 2024',
    sourcePublisher: 'UK DESNZ / DEFRA & IPCC',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024 / IPCC AR4 WG1 Table 2.14',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Refrigerant & other / Table: Individual refrigerants / HFC-134a',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'HFC',
    blendComposition: '100% 1,1,1,2-Tetrafluoroethane (pure chemical substance)',
    description: 'DEFRA 2024 / IPCC - Refrigerant R-134a (Pure HFC-134a, GWP-100 = 1430)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'LEAKAGE_RATE',
    activitySubType: 'r-22',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1810.0,
    co2Factor: 0,
    ch4Factor: 0,
    n2oFactor: 0,
    hfcFactor: 0, // Classified as HCFC Ozone-Depleting Substance, NOT an HFC!
    gwpBasis: 'AR4/DEFRA 2024',
    sourcePublisher: 'UK DESNZ / DEFRA & Montreal Protocol',
    datasetNameAndVersion: 'UK GHG Conversion Factors 2024 / Montreal Protocol Annex C',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Refrigerant & other / Table: Individual refrigerants / HCFC-22',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'HCFC',
    blendComposition: '100% Chlorodifluoromethane (HCFC-22, Ozone-Depleting Substance)',
    description: 'DEFRA 2024 / Montreal Protocol - Refrigerant R-22 (HCFC-22 Ozone Depleting Substance, GWP-100 = 1810)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'LEAKAGE_RATE',
    activitySubType: 'co2 (fire extinguisher)',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1.0,
    co2Factor: 1.0,
    ch4Factor: 0,
    n2oFactor: 0,
    hfcFactor: 0,
    gwpBasis: 'AR6',
    sourcePublisher: 'Pending Authoritative Review',
    datasetNameAndVersion: 'Awaiting GHG Protocol Scope 1 Fire Suppression Guidance',
    pubYear: 2024,
    documentSheetTableRef: 'Pending Guidance',
    authoritativeSourceUrl: 'https://ghgprotocol.org/corporate-standard',
    gasFamily: 'Carbon Dioxide',
    blendComposition: '100% CO2',
    description: '[SOURCE_REQUIRED] Pure CO2 Fire Suppressant - Awaiting authoritative reporting methodology and applicability guidelines under GHG Protocol Scope 1',
    isActive: false, // EXPLICITLY INACTIVE / SOURCE_REQUIRED!
  },

  // ─── Scope 2: Purchased Electricity (Location-Based) ──────────────────────
  {
    factorVersionId: 1, // DEFRA 2024
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'uk national grid',
    geography: 'GB',
    withRF: false,
    factor: 0.20705,
    co2Factor: 0.20520,
    ch4Factor: 0.00045,
    n2oFactor: 0.00140,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: UK electricity / Table: Electricity generated',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Electricity Grid',
    blendComposition: null,
    description: 'DEFRA 2024 - UK National Grid Average Electricity (Location-Based: 0.20705 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'grid electricity',
    geography: 'GB',
    withRF: false,
    factor: 0.20705,
    co2Factor: 0.20520,
    ch4Factor: 0.00045,
    n2oFactor: 0.00140,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: UK electricity / Table: Electricity generated',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Electricity Grid',
    blendComposition: null,
    description: 'DEFRA 2024 - Grid Electricity (Location-Based UK Average: 0.20705 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'dewa grid',
    geography: 'AE',
    withRF: false,
    factor: 0.38800,
    co2Factor: 0.38800,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'AR5',
    sourcePublisher: 'Dubai Electricity and Water Authority (DEWA)',
    datasetNameAndVersion: 'DEWA Sustainability Report 2023',
    pubYear: 2023,
    documentSheetTableRef: 'Environmental Performance Section / Grid Emission Factor Table',
    authoritativeSourceUrl: 'https://www.dewa.gov.ae',
    gasFamily: 'Electricity Grid',
    blendComposition: null,
    description: 'DEWA 2023 - Dubai Electricity Grid Average (Location-Based: 0.38800 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'india central grid',
    geography: 'IN',
    withRF: false,
    factor: 0.71600,
    co2Factor: 0.71600,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'AR5',
    sourcePublisher: 'Central Electricity Authority (CEA), Ministry of Power, Government of India',
    datasetNameAndVersion: 'CO2 Baseline Database for the Indian Power Sector User Guide Version 19.0',
    pubYear: 2023,
    documentSheetTableRef: 'Section 4: Combined Margin Grid Baseline Factor',
    authoritativeSourceUrl: 'https://cea.nic.in',
    gasFamily: 'Electricity Grid',
    blendComposition: null,
    description: 'CEA v19 - Indian National Grid Combined Margin Baseline (Location-Based: 0.71600 kgCO2e/kWh)',
    isActive: true,
  },

  // ─── Scope 2: Purchased Electricity (Market-Based) ────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'certified green ppa',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.00000,
    co2Factor: 0,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'GHG Protocol Scope 2 Guidance',
    sourcePublisher: 'Contractual Instrument (GoO / I-REC / PPA)',
    datasetNameAndVersion: 'GHG Protocol Scope 2 Guidance Market-Based Quality Criteria',
    pubYear: 2024,
    documentSheetTableRef: 'Retired Attribute Serial Certificate / Quality Criteria Verified',
    authoritativeSourceUrl: 'https://ghgprotocol.org/scope-2-guidance',
    gasFamily: 'Renewable Electricity',
    blendComposition: null,
    description: 'Certified Zero-Carbon Renewable Energy Attribute / PPA (Market-Based: 0.00000 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'renewable solar ppa',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.00000,
    co2Factor: 0,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'GHG Protocol Scope 2 Guidance',
    sourcePublisher: 'Contractual Instrument (GoO / I-REC / PPA)',
    datasetNameAndVersion: 'GHG Protocol Scope 2 Guidance Market-Based Quality Criteria',
    pubYear: 2024,
    documentSheetTableRef: 'Retired Attribute Serial Certificate / Quality Criteria Verified',
    authoritativeSourceUrl: 'https://ghgprotocol.org/scope-2-guidance',
    gasFamily: 'Renewable Electricity',
    blendComposition: null,
    description: 'Certified Solar PPA Direct Off-take (Market-Based: 0.00000 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'residual grid mix',
    geography: 'EU',
    withRF: false,
    factor: 0.26500,
    co2Factor: 0.26500,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'AIB 2023',
    sourcePublisher: 'Association of Issuing Bodies (AIB)',
    datasetNameAndVersion: 'European Residual Mixes 2023',
    pubYear: 2023,
    documentSheetTableRef: 'Table 1: National Residual Mixes / UK & European Average',
    authoritativeSourceUrl: 'https://www.aib-net.org',
    gasFamily: 'Electricity Grid',
    blendComposition: null,
    description: 'AIB 2023 - European / UK Residual Mix (Market-Based Default: 0.26500 kgCO2e/kWh)',
    isActive: true,
  },

  // ─── Scope 2: Purchased Heat & Cooling ─────────────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'district heating',
    geography: 'GB',
    withRF: false,
    factor: 0.16954,
    co2Factor: 0.16820,
    ch4Factor: 0.00034,
    n2oFactor: 0.00100,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Heat and steam / Table: District heat and steam',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'District Energy',
    blendComposition: null,
    description: 'DEFRA 2024 - District Heat and Steam (0.16954 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'district chilled water',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.14200,
    co2Factor: 0.14200,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'Utility Disclosure 2023',
    sourcePublisher: 'Regional Utility Environmental Audit',
    datasetNameAndVersion: 'District Cooling Environmental Performance Report 2023',
    pubYear: 2023,
    documentSheetTableRef: 'Chiller Plant COP Efficiency Allocation Table',
    authoritativeSourceUrl: 'https://ghgprotocol.org/corporate-standard',
    gasFamily: 'District Energy',
    blendComposition: null,
    description: 'Regional Utility Disclosure - District Chilled Water (0.14200 kgCO2e/kWh)',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'industrial steam',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.18000,
    co2Factor: 0.18000,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'Facility Specific',
    sourcePublisher: 'Facility Specific Cogeneration Log',
    datasetNameAndVersion: 'On-site Steam Boiler / Cogeneration Audit',
    pubYear: 2024,
    documentSheetTableRef: 'Facility Steam Meter Log',
    authoritativeSourceUrl: 'https://ghgprotocol.org/corporate-standard',
    gasFamily: 'Industrial Steam',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] Industrial Steam - Facility specific boiler / cogeneration factor required',
    isActive: false, // Inactive / SOURCE_REQUIRED
  },

  // ─── Scope 3 Cat 1: Purchased Goods and Services ─────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'SPEND_EEIO',
    activitySubType: 'it and professional services',
    geography: 'US',
    withRF: false,
    factor: 0.18500,
    co2Factor: 0.18500,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'AR5',
    sourcePublisher: 'US Environmental Protection Agency (EPA)',
    datasetNameAndVersion: 'Supply Chain GHG Emission Factors for US Commodities and Industries v2.0',
    pubYear: 2023,
    documentSheetTableRef: 'Table 1 / Code 541512: Computer Systems Design and Related Services',
    authoritativeSourceUrl: 'https://www.epa.gov/climateleadership/supply-chain-guidance',
    gasFamily: 'EEIO Scope 3',
    blendComposition: null,
    description: 'US EPA EEIO v2.0 - IT and Professional Services (0.18500 kgCO2e/USD)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'MASS_BASED',
    activitySubType: 'paper and board',
    geography: 'GB',
    withRF: false,
    factor: 0.85200,
    co2Factor: 0.84200,
    ch4Factor: 0.00500,
    n2oFactor: 0.00500,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Material use / Table: Paper and board: mixed',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Raw Materials',
    blendComposition: null,
    description: 'DEFRA 2024 - Paper and Board Material Use (0.85200 kgCO2e/kg)',
    isActive: true,
  },

  // ─── Scope 3 Cat 2: Capital Goods ─────────────────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'SPEND_EEIO',
    activitySubType: 'industrial machinery',
    geography: 'US',
    withRF: false,
    factor: 0.31500,
    co2Factor: 0.31500,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'AR5',
    sourcePublisher: 'US Environmental Protection Agency (EPA)',
    datasetNameAndVersion: 'Supply Chain GHG Emission Factors for US Commodities and Industries v2.0',
    pubYear: 2023,
    documentSheetTableRef: 'Table 1 / Code 333249: Industrial Machinery Manufacturing',
    authoritativeSourceUrl: 'https://www.epa.gov/climateleadership/supply-chain-guidance',
    gasFamily: 'EEIO Scope 3',
    blendComposition: null,
    description: 'US EPA EEIO v2.0 - Industrial Machinery Manufacturing (0.31500 kgCO2e/USD)',
    isActive: true,
  },

  // ─── Scope 3 Cat 3: Fuel- and Energy-Related Activities (WTT & T&D) ──────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'FUEL_BASED',
    activitySubType: 'wtt - natural gas',
    geography: 'GB',
    withRF: false,
    factor: 0.28540,
    co2Factor: 0.28000,
    ch4Factor: 0.00400,
    n2oFactor: 0.00140,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: WTT - fuels / Table: Natural Gas (100% GCV)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Well-to-Tank Fuels',
    blendComposition: null,
    description: 'DEFRA 2024 - WTT Natural Gas (100% GCV) (0.28540 kgCO2e/sm3)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 't&d grid loss uk',
    geography: 'GB',
    withRF: false,
    factor: 0.01780,
    co2Factor: 0.01750,
    ch4Factor: 0.00010,
    n2oFactor: 0.00020,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Transmission and distribution / Table: T&D UK electricity',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'T&D Loss',
    blendComposition: null,
    description: 'DEFRA 2024 - Transmission & Distribution Losses UK Grid (0.01780 kgCO2e/kWh)',
    isActive: true,
  },

  // ─── Scope 3 Cat 4: Upstream Freight ──────────────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_WEIGHT',
    activitySubType: 'hgv rigid road freight',
    geography: 'GB',
    withRF: false,
    factor: 0.15432,
    co2Factor: 0.15200,
    ch4Factor: 0.00032,
    n2oFactor: 0.00200,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Freighting goods / Table: HGV (all diesel) rigid (>7.5t-17t)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Road Freight',
    blendComposition: null,
    description: 'DEFRA 2024 - HGV Rigid Road Freight (>7.5t-17t) (0.15432 kgCO2e/tkm)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_WEIGHT',
    activitySubType: 'cargo ship sea freight',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.01524,
    co2Factor: 0.01500,
    ch4Factor: 0.00004,
    n2oFactor: 0.00020,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Freighting goods / Table: Cargo ship - general cargo - average',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Sea Freight',
    blendComposition: null,
    description: 'DEFRA 2024 - General Cargo Ship Sea Freight (0.01524 kgCO2e/tkm)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_WEIGHT',
    activitySubType: 'air freight long-haul',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.58240,
    co2Factor: 0.57500,
    ch4Factor: 0.00040,
    n2oFactor: 0.00700,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Freighting goods / Table: Freight flights - long haul',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Air Freight',
    blendComposition: null,
    description: 'DEFRA 2024 - Long-Haul Air Freight (0.58240 kgCO2e/tkm)',
    isActive: true,
  },

  // ─── Scope 3 Cat 5: Waste Generated in Operations ────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'MASS_BASED',
    activitySubType: 'commercial waste to landfill',
    geography: 'GB',
    withRF: false,
    factor: 0.46705,
    co2Factor: 0.46500,
    ch4Factor: 0.00150,
    n2oFactor: 0.00055,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Waste disposal / Table: Commercial and industrial waste',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Waste Disposal',
    blendComposition: null,
    description: 'DEFRA 2024 - Commercial Waste to Landfill (0.46705 kgCO2e/kg)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'MASS_BASED',
    activitySubType: 'paper closed-loop recycling',
    geography: 'GB',
    withRF: false,
    factor: 0.02132,
    co2Factor: 0.02100,
    ch4Factor: 0.00012,
    n2oFactor: 0.00020,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Waste disposal / Table: Paper and board closed loop',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Waste Recycling',
    blendComposition: null,
    description: 'DEFRA 2024 - Paper and Board Closed-Loop Recycling (0.02132 kgCO2e/kg)',
    isActive: true,
  },

  // ─── Scope 3 Cat 7: Employee Commuting ────────────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'commuting car petrol',
    geography: 'GB',
    withRF: false,
    factor: 0.17048,
    co2Factor: 0.16890,
    ch4Factor: 0.00018,
    n2oFactor: 0.00140,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Passenger vehicles / Table: Petrol car (average)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Passenger Vehicle',
    blendComposition: null,
    description: 'DEFRA 2024 - Employee Commuting Passenger Car (Petrol Average: 0.17048 kgCO2e/km)',
    isActive: true,
  },
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_BASED',
    activitySubType: 'commuting motorcycle',
    geography: 'GB',
    withRF: false,
    factor: 0.10125,
    co2Factor: 0.10000,
    ch4Factor: 0.00025,
    n2oFactor: 0.00100,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Passenger vehicles / Table: Medium motorcycle (125-500cc)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Passenger Vehicle',
    blendComposition: null,
    description: 'DEFRA 2024 - Employee Commuting Motorcycle (Medium 125-500cc: 0.10125 kgCO2e/km)',
    isActive: true,
  },

  // ─── Scope 3 Cat 8: Upstream Leased Assets ────────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'leased office energy',
    geography: 'GB',
    withRF: false,
    factor: 0.20000,
    co2Factor: 0.20000,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'CIBSE Guide F',
    sourcePublisher: 'Chartered Institution of Building Services Engineers (CIBSE)',
    datasetNameAndVersion: 'CIBSE Energy Benchmark Guide F',
    pubYear: 2023,
    documentSheetTableRef: 'Table 20.1 / Benchmark Category: General Office Air Conditioned',
    authoritativeSourceUrl: 'https://www.cibse.org',
    gasFamily: 'Building Benchmark',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] CIBSE Guide F - Leased Office Building Energy Benchmark (0.20000 kgCO2e/m2)',
    isActive: false, // Candidate awaiting tenant submeter verification
  },

  // ─── Scope 3 Cat 9: Downstream Freight ────────────────────────────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'DISTANCE_WEIGHT',
    activitySubType: 'downstream articulated hgv',
    geography: 'GB',
    withRF: false,
    factor: 0.10820,
    co2Factor: 0.10650,
    ch4Factor: 0.00020,
    n2oFactor: 0.00150,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Freighting goods / Table: Articulated HGV (>33t)',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Road Freight',
    blendComposition: null,
    description: 'DEFRA 2024 - Downstream Distribution Articulated HGV (>33t: 0.10820 kgCO2e/tkm)',
    isActive: true,
  },

  // ─── Scope 3 Cat 10: Processing of Sold Products ─────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'MASS_BASED',
    activitySubType: 'intermediate product processing',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.15000,
    co2Factor: 0.15000,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'Facility Specific',
    sourcePublisher: '3rd Party Intermediate Processor Audit',
    datasetNameAndVersion: 'Intermediate Product Processing Environmental Product Declaration (EPD)',
    pubYear: 2024,
    documentSheetTableRef: 'Section 3: Energy Allocation per Product Output Tonne',
    authoritativeSourceUrl: 'https://ghgprotocol.org/standards/scope-3-standard',
    gasFamily: 'Product Processing',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] 3rd Party Intermediate Processing - Processor EPD required',
    isActive: false, // Candidate awaiting processor EPD
  },

  // ─── Scope 3 Cat 11: Use of Sold Products ────────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'product lifetime electricity',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.20705,
    co2Factor: 0.20705,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'OEM Technical Spec',
    sourcePublisher: 'OEM Product Rating / Energy Star Specification',
    datasetNameAndVersion: 'Product Rating Life Cycle Specification',
    pubYear: 2024,
    documentSheetTableRef: 'Rated Lifetime Operating kWh',
    authoritativeSourceUrl: 'https://ghgprotocol.org/standards/scope-3-standard',
    gasFamily: 'Product In-Use',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] Use of Sold Products - OEM product technical specification required',
    isActive: false, // Candidate awaiting OEM specification
  },

  // ─── Scope 3 Cat 12: End-of-Life Treatment of Sold Products ──────────────
  {
    factorVersionId: 1,
    unitId: 1,
    calculationMethod: 'MASS_BASED',
    activitySubType: 'mixed plastics recycling',
    geography: 'GB',
    withRF: false,
    factor: 0.03450,
    co2Factor: 0.03400,
    ch4Factor: 0.00010,
    n2oFactor: 0.00040,
    gwpBasis: 'AR4',
    sourcePublisher: 'UK Department for Energy Security and Net Zero (DESNZ) / DEFRA',
    datasetNameAndVersion: '2024 UK Government GHG Conversion Factors for Company Reporting',
    pubYear: 2024,
    documentSheetTableRef: 'Full Set / Sheet: Waste disposal / Table: Mixed plastics recycling',
    authoritativeSourceUrl: 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024',
    gasFamily: 'Waste Recycling',
    blendComposition: null,
    description: 'DEFRA 2024 - Mixed Plastics End-of-Life Recycling (0.03450 kgCO2e/kg)',
    isActive: true,
  },

  // ─── Scope 3 Cat 13: Downstream Leased Assets ─────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'downstream leased facility',
    geography: 'GB',
    withRF: false,
    factor: 0.25000,
    co2Factor: 0.25000,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'EPC Register',
    sourcePublisher: 'Commercial Energy Performance Certificate Register',
    datasetNameAndVersion: 'Commercial EPC Asset Rating Database',
    pubYear: 2024,
    documentSheetTableRef: 'Asset EPC Rating Sheet',
    authoritativeSourceUrl: 'https://ghgprotocol.org/standards/scope-3-standard',
    gasFamily: 'Leased Property',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] Downstream Leased Assets - Asset EPC rating or tenant submeter data required',
    isActive: false, // Candidate awaiting tenant data
  },

  // ─── Scope 3 Cat 14: Franchises ───────────────────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'ENERGY_BASED',
    activitySubType: 'franchise energy',
    geography: 'GLOBAL',
    withRF: false,
    factor: 0.20705,
    co2Factor: 0.20705,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'Franchise Disclosure',
    sourcePublisher: 'Franchise Partner Environmental Billing',
    datasetNameAndVersion: 'Franchise Utility Meter Log',
    pubYear: 2024,
    documentSheetTableRef: 'Branch Utility Invoice',
    authoritativeSourceUrl: 'https://ghgprotocol.org/standards/scope-3-standard',
    gasFamily: 'Franchise Operations',
    blendComposition: null,
    description: '[SOURCE_REQUIRED] Franchise Operations - Verified branch utility invoices required',
    isActive: false, // Candidate awaiting franchise billing
  },

  // ─── Scope 3 Cat 15: Investments ──────────────────────────────────────────
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'INVESTMENT_EQUITY',
    activitySubType: 'financed equity share',
    geography: 'GLOBAL',
    withRF: false,
    factor: 1.00000,
    co2Factor: 1.00000,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'PCAF Standard',
    sourcePublisher: 'Partnership for Carbon Accounting Financials (PCAF)',
    datasetNameAndVersion: 'The Global GHG Accounting and Reporting Standard for the Financial Industry',
    pubYear: 2024,
    documentSheetTableRef: 'Chapter 5 / Section 5.1: Listed Equity and Corporate Bonds',
    authoritativeSourceUrl: 'https://carbonaccountingfinancials.com',
    gasFamily: 'Financed Emissions',
    blendComposition: null,
    description: 'PCAF 2024 - Financed Emissions Proportional Equity Share Calculation',
    isActive: true,
  },
  {
    factorVersionId: 2,
    unitId: 1,
    calculationMethod: 'INVESTMENT_AVERAGE_DATA',
    activitySubType: 'financed sector average',
    geography: 'US',
    withRF: false,
    factor: 0.24500,
    co2Factor: 0.24500,
    ch4Factor: 0,
    n2oFactor: 0,
    gwpBasis: 'PCAF / US EPA',
    sourcePublisher: 'PCAF & US EPA EEIO',
    datasetNameAndVersion: 'PCAF Economic Intensity Database v2.0',
    pubYear: 2024,
    documentSheetTableRef: 'Sector Intensity Table / Code 522: Credit Intermediation',
    authoritativeSourceUrl: 'https://carbonaccountingfinancials.com',
    gasFamily: 'Financed Emissions',
    blendComposition: null,
    description: 'PCAF / EPA EEIO - Financed Emissions Sector Average Economic Intensity (0.24500 kgCO2e/USD)',
    isActive: true,
  },
];
