import { GwpSet } from 'src/entities/gwp-set.entity';
import { GwpValue } from 'src/entities/gwp-value.entity';
import { MasterFuel } from 'src/entities/master-fuel.entity';
import { MasterFactorVersion } from 'src/entities/master-factor-version.entity';
import { MasterUnit } from 'src/entities/master-unit.entity';
import { EmissionFactor } from 'src/entities/emission-factor.entity';
import { UnitConversion } from 'src/entities/unit-conversion.entity';
import { ApprovalModules, ApprovalMatrix } from 'src/entities/approval.entity';

export const SEED_GWP_SET: Partial<GwpSet> = {
  name: 'IPCC AR6 (100-year)',
  source: 'IPCC Sixth Assessment Report',
  assessment: 'AR6',
  timeHorizon: 100,
  version: '2023',
  isCurrent: true,
  isFossilMethaneDistinguished: true,
  description:
    '100-year global warming potentials from IPCC AR6 WG1 (2021), fossil/non-fossil methane distinguished.',
  isActive: true,
};

export const SEED_GWP_VALUES: Partial<GwpValue>[] = [
  {
    gasCode: 'CO2',
    gasName: 'Carbon Dioxide',
    chemicalFormula: 'CO2',
    value: 1,
    methaneOrigin: null,
    isActive: true,
  },
  {
    gasCode: 'CH4',
    gasName: 'Methane (fossil)',
    chemicalFormula: 'CH4',
    value: 29.8,
    methaneOrigin: 'FOSSIL',
    isActive: true,
  },
  {
    gasCode: 'CH4',
    gasName: 'Methane (non-fossil)',
    chemicalFormula: 'CH4',
    value: 27.0,
    methaneOrigin: 'NON_FOSSIL',
    isActive: true,
  },
  {
    gasCode: 'N2O',
    gasName: 'Nitrous Oxide',
    chemicalFormula: 'N2O',
    value: 273,
    methaneOrigin: null,
    isActive: true,
  },
  {
    gasCode: 'HFC',
    gasName: 'Hydrofluorocarbons',
    chemicalFormula: '-',
    value: 1460,
    methaneOrigin: null,
    isActive: true,
  },
  {
    gasCode: 'PFC',
    gasName: 'Perfluorocarbons',
    chemicalFormula: '-',
    value: 7380,
    methaneOrigin: null,
    isActive: true,
  },
  {
    gasCode: 'SF6',
    gasName: 'Sulphur Hexafluoride',
    chemicalFormula: 'SF6',
    value: 25200,
    methaneOrigin: null,
    isActive: true,
  },
  {
    gasCode: 'NF3',
    gasName: 'Nitrogen Trifluoride',
    chemicalFormula: 'NF3',
    value: 16100,
    methaneOrigin: null,
    isActive: true,
  },
];

export const SEED_MASTER_UNITS: Partial<MasterUnit>[] = [
  {
    name: 'Kilogram CO2 Equivalent',
    symbol: 'kgCO2e',
    description: 'Output unit for factor values',
    isActive: true,
  },
  {
    name: 'Standard Cubic Metre',
    symbol: 'sm3',
    description: 'Natural gas volume',
    isActive: true,
  },
  {
    name: 'Litre',
    symbol: 'L',
    description: 'Liquid fuel volume',
    isActive: true,
  },
  { name: 'Kilogram', symbol: 'kg', description: 'Mass', isActive: true },
  {
    name: 'Kilowatt Hour',
    symbol: 'kWh',
    description: 'Electrical energy',
    isActive: true,
  },
  {
    name: 'Megawatt Hour',
    symbol: 'MWh',
    description: 'Electrical energy (bulk)',
    isActive: true,
  },
  {
    name: 'Cubic Metre',
    symbol: 'm3',
    description: 'Gas volume',
    isActive: true,
  },
  {
    name: 'Metric Tonne',
    symbol: 'tonne',
    description: 'Mass (1000 kg)',
    isActive: true,
  },
  {
    name: 'Ton',
    symbol: 'ton',
    description: 'Mass (1000 kg, reporting alias)',
    isActive: true,
  },
  { name: 'Kilometre', symbol: 'km', description: 'Distance', isActive: true },
  {
    name: 'Tonne-Kilometre',
    symbol: 't-km',
    description: 'Freight distance',
    isActive: true,
  },
  {
    name: 'Passenger-Kilometre',
    symbol: 'passenger.km',
    description: 'Passenger distance',
    isActive: true,
  },
  {
    name: 'US Dollar',
    symbol: 'USD',
    description: 'Spend-based factors',
    isActive: true,
  },
];

export const SEED_MASTER_FACTOR_VERSIONS: Partial<MasterFactorVersion>[] = [
  {
    version: 'AR6-2024',
    year: 2024,
    description: 'DEFRA GHG Conversion Factors 2024 / IPCC AR6',
    isActive: true,
  },
  {
    version: 'IEA-2023',
    year: 2023,
    description: 'IEA Grid Emission Factors 2023',
    isActive: true,
  },
];

export const SEED_MASTER_FUELS: Partial<MasterFuel>[] = [
  {
    name: 'Natural Gas',
    code: 'NAT_GAS',
    scopeId: 1,
    description: 'Grid natural gas',
    isActive: true,
  },
  {
    name: 'Diesel',
    code: 'DIESEL',
    scopeId: 1,
    description: 'Diesel fuel (stationary)',
    isActive: true,
  },
  {
    name: 'Diesel - On Road Fleet',
    code: 'DIESEL_ROAD',
    scopeId: 1,
    description: 'Diesel for road vehicles',
    isActive: true,
  },
  {
    name: 'Refrigerant R-134a',
    code: 'HFC_134A',
    scopeId: 1,
    description: 'HFC refrigerant (AR6 GWP 1460)',
    isActive: true,
  },
  {
    name: 'Grid Electricity',
    code: 'GRID_ELEC',
    scopeId: 2,
    description: 'Purchased grid electricity',
    isActive: true,
  },
];

export const SEED_EMISSION_FACTORS: Partial<EmissionFactor>[] = [
  {
    fuelId: 1,
    factorVersionId: 1,
    unitBasisId: 2,
    geography: 'GLOBAL',
    reportingYear: 2025,
    methodology: 'AR6 (Commercial & Institutional Use)',
    methodologyStatus: 'CURRENT',
    factorValue: 1.942,
    co2Value: 1.927,
    ch4Value: 0.0049,
    n2oValue: 0.0009,
    biogenicCo2Value: 0,
    isFossilMethane: true,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'DEFRA GHG Conversion Factors 2024 / IPCC AR6',
    isDefaultFactor: true,
    description: 'Natural gas per sm3',
    isActive: true,
  },
  {
    fuelId: 2,
    factorVersionId: 1,
    unitBasisId: 3,
    geography: 'GLOBAL',
    reportingYear: 2025,
    methodology: 'DEFRA 2024',
    methodologyStatus: 'CURRENT',
    factorValue: 2.684,
    co2Value: 2.678,
    ch4Value: 0.003,
    n2oValue: 0.003,
    biogenicCo2Value: 0,
    isFossilMethane: true,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'DEFRA GHG Conversion Factors 2024',
    isDefaultFactor: true,
    description: 'Diesel (stationary) per litre',
    isActive: true,
  },
  {
    fuelId: 3,
    factorVersionId: 1,
    unitBasisId: 3,
    geography: 'GLOBAL',
    reportingYear: 2025,
    methodology: 'IPCC AR6',
    methodologyStatus: 'CURRENT',
    factorValue: 2.666,
    co2Value: 2.661,
    ch4Value: 0.002,
    n2oValue: 0.003,
    biogenicCo2Value: 0,
    isFossilMethane: true,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'DEFRA GHG Conversion Factors 2024',
    isDefaultFactor: true,
    description: 'Diesel on-road fleet per litre',
    isActive: true,
  },
  {
    fuelId: 4,
    factorVersionId: 1,
    unitBasisId: 4,
    geography: 'GLOBAL',
    reportingYear: 2025,
    methodology: 'IPCC AR6 GWP',
    methodologyStatus: 'CURRENT',
    factorValue: 1460,
    hfcValue: 1460,
    biogenicCo2Value: 0,
    isFossilMethane: false,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'IPCC AR6 (2021)',
    isDefaultFactor: true,
    description: 'HFC-134a refrigerant per kg (GWP-weighted)',
    isActive: true,
  },
  {
    fuelId: 5,
    factorVersionId: 2,
    unitBasisId: 5,
    geography: 'TÜRKİYE',
    reportingYear: 2024,
    methodology: 'IEA 2023 grid factor',
    methodologyStatus: 'CURRENT',
    factorValue: 0.442,
    co2Value: 0.442,
    biogenicCo2Value: 0,
    isFossilMethane: false,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'IEA Grid Emission Factors 2023',
    isDefaultFactor: false,
    description: 'Türkiye grid electricity per kWh',
    isActive: true,
  },
  {
    fuelId: 5,
    factorVersionId: 2,
    unitBasisId: 5,
    geography: 'UK',
    reportingYear: 2025,
    methodology: 'DEFRA UK Grid 2024',
    methodologyStatus: 'CURRENT',
    factorValue: 0.207,
    co2Value: 0.207,
    biogenicCo2Value: 0,
    isFossilMethane: false,
    outputUnit: 'kgCO2e',
    dataQuality: 'AVERAGE_DATA',
    sourceReference: 'DEFRA UK Grid 2024',
    isDefaultFactor: false,
    description: 'UK grid electricity per kWh',
    isActive: true,
  },
];

export const SEED_UNIT_CONVERSIONS: Partial<UnitConversion>[] = [
  {
    fromUnit: 'kWh',
    toUnit: 'MWh',
    conversionFactor: 0.001,
    source: 'SI prefix',
    description: 'kilo to mega',
    isActive: true,
  },
  {
    fromUnit: 'MWh',
    toUnit: 'kWh',
    conversionFactor: 1000,
    source: 'SI prefix',
    description: 'mega to kilo',
    isActive: true,
  },
  {
    fromUnit: 'tonne',
    toUnit: 'kg',
    conversionFactor: 1000,
    source: 'SI',
    description: 'metric tonne to kg',
    isActive: true,
  },
  {
    fromUnit: 'ton',
    toUnit: 'kg',
    conversionFactor: 1000,
    source: 'SI (reporting alias)',
    description: 'ton to kg',
    isActive: true,
  },
  {
    fromUnit: 'kg',
    toUnit: 'tonne',
    conversionFactor: 0.001,
    source: 'SI',
    description: 'kg to metric tonne',
    isActive: true,
  },
];

export const SEED_APPROVAL_MODULE_INVENTORY: Partial<ApprovalModules> = {
  id: 2,
  moduleName: 'Inventory Entry Approval',
  moduleShortName: 'INVENTORY_ENTRY',
  mappingTable: 'inventory_entries',
  mappingColumn: 'id',
  isActive: true,
};

export const SEED_APPROVAL_MATRIX_INVENTORY: Partial<ApprovalMatrix>[] = [
  {
    approvalModuleId: 2,
    conditionName: '"isActive" = true',
    fieldName: 'None',
    toRoleId: 1,
    approvalOrder: 1,
    approvalGroup: 1,
    isParallel: false,
    isActive: true,
  },
  {
    approvalModuleId: 2,
    conditionName: '"emission" > 100',
    fieldName: 'None',
    toRoleId: 2,
    approvalOrder: 2,
    approvalGroup: 1,
    isParallel: false,
    isActive: true,
  },
];
