import { Service } from 'src/entities/service.entity';
import { ServiceScopeItem } from 'src/entities/service-scope-item.entity';
import { EmissionFactor } from 'src/entities/emission-factor.entity';
import { InventoryEntry } from 'src/entities/inventory-entry.entity';
import { Facility } from 'src/entities/facility.entity';

export const SEED_SERVICES: Partial<Service>[] = [
  {
    code: 'CARBON',
    name: 'CO2 Suite Carbon',
    description: 'Corporate Carbon Management and GHG Accounting Module',
    category: 'Carbon',
    tags: ['Carbon'],
    demoUrl: '/services/carbon',
    isActive: true,
  },
  {
    code: 'CBAM',
    name: 'CO2 Suite CBAM',
    description: 'EU Carbon Border Adjustment Mechanism Reporting Module',
    category: 'CBAM',
    tags: ['CBAM'],
    demoUrl: '/services/cbam',
    isActive: true,
  },
  {
    code: 'PEF_TEXTILES',
    name: 'CO2 Suite PEF',
    description:
      'EU Product Environmental Footprint Module for Textiles & Apparels',
    category: 'PEF',
    tags: ['PEF', 'Textiles & Apparels'],
    demoUrl: '/services/pef_textiles',
    isActive: true,
  },
  {
    code: 'LCA_PLASTICS',
    name: 'CO2 Suite LCA',
    description: 'Product Life Cycle Assessment for Plastic Manufacturing',
    category: 'LCA',
    tags: ['LCA', 'Plastics'],
    demoUrl: '/services/lca_plastics',
    isActive: true,
  },
  {
    code: 'LCA_METALS',
    name: 'CO2 Suite LCA',
    description: 'Product Life Cycle Assessment for Metal Manufacturing',
    category: 'LCA',
    tags: ['LCA', 'Metals'],
    demoUrl: '/services/lca_metals',
    isActive: true,
  },
  {
    code: 'ESG',
    name: 'CO2 Suite ESG',
    description:
      'Corporate Sustainability Management and CSRD Reporting Module',
    category: 'ESG',
    tags: ['ESG'],
    demoUrl: '/services/esg',
    isActive: true,
  },
  {
    code: 'EPD_CABLES',
    name: 'CO2 Suite EPD',
    description: 'Environmental Product Declarations Module for Cable Industry',
    category: 'EPD',
    tags: ['EPD', 'Cables'],
    demoUrl: '/services/epd_cables',
    isActive: true,
  },
];

export const SEED_SCOPE_ITEMS: Partial<ServiceScopeItem>[] = [
  // Scope 1
  {
    serviceCode: 'CARBON',
    scope: 'Scope 1',
    scopeCode: 'SCOPE_1',
    name: 'Stationary Combustion',
    code: 'STATIONARY_COMBUSTION',
    description: 'Fuel burnt in stationary boilers, heaters, and generators',
    sortOrder: 1,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 1',
    scopeCode: 'SCOPE_1',
    name: 'Mobile Combustion',
    code: 'MOBILE_COMBUSTION',
    description: 'Fuel burnt in company owned/leased vehicles and machinery',
    sortOrder: 2,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 1',
    scopeCode: 'SCOPE_1',
    name: 'Fugitive Emissions',
    code: 'FUGITIVE_EMISSIONS',
    description: 'Refrigerants, HVAC leaks, and gas escapes',
    sortOrder: 3,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 1',
    scopeCode: 'SCOPE_1',
    name: 'Process Emissions',
    code: 'PROCESS_EMISSIONS',
    description: 'Emissions from chemical and physical manufacturing processes',
    sortOrder: 4,
    isActive: true,
  },

  // Scope 2
  {
    serviceCode: 'CARBON',
    scope: 'Scope 2',
    scopeCode: 'SCOPE_2',
    name: 'Purchased Electricity',
    code: 'PURCHASED_ELECTRICITY',
    description: 'Grid electricity consumption across facility sites',
    sortOrder: 1,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 2',
    scopeCode: 'SCOPE_2',
    name: 'Purchased Heating & Steam',
    code: 'PURCHASED_HEATING_STEAM',
    description: 'District heating, cooling, and industrial steam',
    sortOrder: 2,
    isActive: true,
  },

  // Scope 3
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Purchased Goods and Services',
    code: 'PURCHASED_GOODS_SERVICES',
    description: 'Upstream supply chain products, raw materials and services',
    sortOrder: 1,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Capital Goods',
    code: 'CAPITAL_GOODS',
    description: 'Capital equipment, IT hardware, and facility infrastructure',
    sortOrder: 2,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Energy and Fuel Related Activities',
    code: 'ENERGY_FUEL_ACTIVITIES',
    description: 'WTT fuel extraction, refining and grid T&D losses',
    sortOrder: 3,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Upstream Transportation',
    code: 'UPSTREAM_TRANSPORTATION',
    description:
      'Inbound freight and logistics by 3rd party logistics providers',
    sortOrder: 4,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Waste Generated in Operations',
    code: 'WASTE_GENERATED_OPERATIONS',
    description: 'Solid waste disposal, wastewater treatment and recycling',
    sortOrder: 5,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Business Travel',
    code: 'BUSINESS_TRAVEL',
    description: 'Commercial flights, train travel, taxis, and hotel stays',
    sortOrder: 6,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Employee Commuting',
    code: 'EMPLOYEE_COMMUTING',
    description: 'Staff commuting between primary residence and workplace',
    sortOrder: 7,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Downstream Transportation',
    code: 'DOWNSTREAM_TRANSPORTATION',
    description: 'Outbound logistics and distribution of sold products',
    sortOrder: 8,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Processing of Sold Products',
    code: 'PROCESSING_SOLD_PRODUCTS',
    description: 'Processing of intermediate goods sold to 3rd parties',
    sortOrder: 9,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Use of Sold Products',
    code: 'USE_SOLD_PRODUCTS',
    description: 'Direct energy and emissions during product use phase',
    sortOrder: 10,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'EOL Treatment of Sold Products',
    code: 'EOL_TREATMENT_SOLD_PRODUCTS',
    description: 'End of life disposal, landfilling, and recycling of products',
    sortOrder: 11,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Franchise',
    code: 'FRANCHISE',
    description: 'Emissions from independent franchise operations',
    sortOrder: 12,
    isActive: true,
  },
  {
    serviceCode: 'CARBON',
    scope: 'Scope 3',
    scopeCode: 'SCOPE_3',
    name: 'Investments',
    code: 'INVESTMENTS',
    description: 'Financed emissions and corporate equity investments',
    sortOrder: 13,
    isActive: true,
  },
];

export const SEED_EMISSION_FACTORS: Partial<EmissionFactor>[] = [
  // Stationary Combustion
  {
    category: 'Stationary Combustion',
    source: 'IPCC (Commercial Use)-AR6',
    version: 'AR6',
    fuelOrGasType: 'Natural Gas',
    unit: 'sm3',
    factor: 1.942,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Stationary Combustion',
    source: 'IPCC (Manufacturing)-AR6',
    version: 'AR6',
    fuelOrGasType: 'Natural Gas',
    unit: 'sm3',
    factor: 1.938,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Stationary Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Diesel Fuel',
    unit: 'L',
    factor: 2.684,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Stationary Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Heavy Fuel Oil',
    unit: 'L',
    factor: 3.178,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Stationary Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'LPG (Liquefied Petroleum Gas)',
    unit: 'L',
    factor: 1.557,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Mobile Combustion
  {
    category: 'Mobile Combustion',
    source: 'IPCC-AR6',
    version: 'AR6',
    fuelOrGasType: 'Diesel - On Road Fleet',
    unit: 'L',
    factor: 2.666,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Mobile Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Petrol - Fleet Cars',
    unit: 'L',
    factor: 2.314,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Mobile Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Light Commercial Van (Diesel)',
    unit: 'km',
    factor: 0.218,
    formula: '(distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Mobile Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'On Road - Diesel',
    unit: 'L',
    factor: 2.684,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Mobile Combustion',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'On Road - Petrol',
    unit: 'L',
    factor: 2.314,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Fugitive & Process Emissions
  {
    category: 'Fugitive Emissions',
    source: 'IPCC-AR6 GWP',
    version: 'AR6',
    fuelOrGasType: 'Refrigerant R-134a',
    unit: 'kg',
    factor: 1430.0,
    formula: '(amount * (leakage / 100) * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Fugitive Emissions',
    source: 'IPCC-AR6 GWP',
    version: 'AR6',
    fuelOrGasType: 'Refrigerant R-410A',
    unit: 'kg',
    factor: 2088.0,
    formula: '(amount * (leakage / 100) * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Process Emissions',
    source: 'IPCC Industrial Processes',
    version: 'AR6',
    fuelOrGasType: 'CO2 Process Release',
    unit: 'kg',
    factor: 1.0,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 2: Purchased Electricity
  {
    category: 'Purchased Electricity',
    source: 'IEA Grid Factors 2023',
    version: '2023',
    fuelOrGasType: 'Republic of Türkiye',
    unit: 'kWh',
    factor: 0.442,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Electricity',
    source: 'DEFRA UK Grid 2024',
    version: '2024',
    fuelOrGasType: 'United Kingdom Grid',
    unit: 'kWh',
    factor: 0.207,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Electricity',
    source: 'IEA Europe 2023',
    version: '2023',
    fuelOrGasType: 'Germany National Grid',
    unit: 'kWh',
    factor: 0.375,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 2: Purchased Heating & Steam
  {
    category: 'Purchased Heating & Steam',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'District Steam (Natural Gas)',
    unit: 'kWh',
    factor: 0.171,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Heating & Steam',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'District Chilled Water',
    unit: 'kWh',
    factor: 0.142,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Purchased Goods
  {
    category: 'Purchased Goods and Services',
    source: 'Ecoinvent 3.9',
    version: 'v3.9',
    fuelOrGasType: 'Aluminium ingot (India)',
    unit: 'kg',
    factor: 8.92,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Goods and Services',
    source: 'Ecoinvent 3.9',
    version: 'v3.9',
    fuelOrGasType: 'Aluminium ingot (Primary EU)',
    unit: 'kg',
    factor: 6.75,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Goods and Services',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Virgin PET Plastic Granules',
    unit: 'kg',
    factor: 2.34,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Purchased Goods and Services',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Corrugated Cardboard Packaging',
    unit: 'kg',
    factor: 0.812,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Capital Goods
  {
    category: 'Capital Goods',
    source: 'EXIOBASE v3.8',
    version: 'v3.8',
    fuelOrGasType: 'Industrial Machinery & Equipment',
    unit: 'USD',
    factor: 0.425,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Upstream & Downstream Transportation
  {
    category: 'Upstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'HGV Freight (Diesel, Laden)',
    unit: 'ton.km',
    factor: 0.121,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Upstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Air Freight (International Long Haul)',
    unit: 'ton.km',
    factor: 0.602,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Upstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Freighting Goods',
    unit: 'ton.km',
    factor: 0.121,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Upstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Heavy Goods Vehicle',
    unit: 'ton.km',
    factor: 0.121,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Downstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Container Sea Cargo Ship',
    unit: 'ton.km',
    factor: 0.016,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Downstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Freighting Goods',
    unit: 'ton.km',
    factor: 0.121,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Downstream Transportation',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Heavy Goods Vehicle',
    unit: 'ton.km',
    factor: 0.121,
    formula: '(distance * amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Waste Generated in Operations
  {
    category: 'Waste Generated in Operations',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Commercial Mixed Waste - Landfill',
    unit: 'tonne',
    factor: 446.2,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Waste Generated in Operations',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Average Construction - Closed Loop',
    unit: 'tonne',
    factor: 0.001,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Waste Generated in Operations',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Glass - Closed Loop',
    unit: 'tonne',
    factor: 6.411,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Waste Generated in Operations',
    source: 'DEFRA 2025',
    version: '2025',
    fuelOrGasType: 'Discharged Wastewater',
    unit: 'm3',
    factor: 0.171,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Waste Generated in Operations',
    source: 'DEFRA 2025',
    version: '2025',
    fuelOrGasType: 'Industrial Wastewater',
    unit: 'm3',
    factor: 0.22,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Business Travel & Employee Commuting
  {
    category: 'Business Travel',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Short Haul - Economy',
    unit: 'passenger.km',
    factor: 0.205,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Business Travel',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Long Haul Flight (Business Class)',
    unit: 'passenger.km',
    factor: 0.254,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Business Travel',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Ferry - Passenger',
    unit: 'passenger.km',
    factor: 0.019,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Business Travel',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Taxi - Regular',
    unit: 'passenger.km',
    factor: 0.15,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Business Travel',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Hotel Stay - Standard',
    unit: 'room-night',
    factor: 14.5,
    formula: '(rooms * nights * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Employee Commuting',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Average Diesel Passenger Car',
    unit: 'km',
    factor: 0.171,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Employee Commuting',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'On Road - Diesel',
    unit: 'km',
    factor: 0.171,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Employee Commuting',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'On Road - Petrol',
    unit: 'km',
    factor: 0.165,
    formula: '(people * distance * factor) / 1000',
    isActive: true,
  },

  // Scope 3: End of Life
  {
    category: 'EOL Treatment of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Metal (Mixed Can) - Closed Loop',
    unit: 'ton',
    factor: 6.411,
    formula: 'amount * factor',
    isActive: true,
  },
  {
    category: 'EOL Treatment of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Paper Board - Landfill Disposal',
    unit: 'ton',
    factor: 1164.489,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'EOL Treatment of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Metal (Mixed Can)',
    unit: 'ton',
    factor: 6.411,
    formula: 'amount * factor',
    isActive: true,
  },
  {
    category: 'EOL Treatment of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Paper Board',
    unit: 'ton',
    factor: 1164.489,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },

  // Scope 3: Other Categories
  {
    category: 'Energy and Fuel Related Activities',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'WTT - Electricity (UK Grid)',
    unit: 'kWh',
    factor: 0.045,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Processing of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Intermediate Metal Processing',
    unit: 'tonne',
    factor: 1.25,
    formula: 'amount * factor',
    isActive: true,
  },
  {
    category: 'Processing of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Manufacturing Facility',
    unit: 'tonne',
    factor: 1.25,
    formula: 'amount * factor',
    isActive: true,
  },
  {
    category: 'Use of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Direct Fuel Use (Equipment)',
    unit: 'L',
    factor: 2.314,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Use of Sold Products',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Consumer Use',
    unit: 'L',
    factor: 2.314,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Franchise',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Franchise Facility Operations',
    unit: 'sqm',
    factor: 45.2,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Franchise',
    source: 'IEA Grid Factors 2023',
    version: '2023',
    fuelOrGasType: 'Electricity Consumption',
    unit: 'kWh',
    factor: 0.442,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Franchise',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Stationary Combustion',
    unit: 'sm3',
    factor: 1.942,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Franchise',
    source: 'DEFRA 2024',
    version: '2024',
    fuelOrGasType: 'Water Consumption',
    unit: 'm3',
    factor: 0.149,
    formula: '(amount * factor) / 1000',
    isActive: true,
  },
  {
    category: 'Investments',
    source: 'PCAF 2023',
    version: '2023',
    fuelOrGasType: 'Equity Investment (Manufacturing)',
    unit: 'USD',
    factor: 0.35,
    formula: '(scope1 + scope2) * (equityShare / 100)',
    isActive: true,
  },
];

export const SEED_INVENTORY_ENTRIES: Partial<InventoryEntry>[] = [
  // Scope 1: Stationary Combustion
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Stationary Combustion',
    name: 'Natural Gas',
    amount: 54200,
    unit: 'sm3',
    ef: 1.942,
    efSource: 'IPCC (Commercial Use)-AR6',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 105.256,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Stationary Combustion',
    name: 'Diesel Fuel',
    amount: 18500,
    unit: 'L',
    ef: 2.684,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 49.654,
    status: 'Approved',
  },

  // Scope 1: Mobile Combustion & Fugitives
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Mobile Combustion',
    name: 'Diesel - On Road Fleet',
    amount: 12400,
    unit: 'L',
    ef: 2.666,
    efSource: 'IPCC-AR6',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 33.058,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Fugitive Emissions',
    name: 'Refrigerant R-134a',
    amount: 28,
    unit: 'kg',
    ef: 1430.0,
    efSource: 'IPCC-AR6 GWP',
    dateFrom: '15.03.2025',
    dateTo: '15.03.2025',
    facility: 'Manchester Facility',
    emission: 40.04,
    status: 'Approved',
  },

  // Scope 2: Purchased Electricity
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Electricity',
    name: 'Republic of Türkiye',
    amount: 32644678,
    unit: 'kWh',
    ef: 0.442,
    efSource: 'IEA Grid Factors 2023',
    dateFrom: '01.01.2024',
    dateTo: '31.12.2024',
    facility: 'WD Solutions Co. LLC',
    emission: 14428.948,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Electricity',
    name: 'United Kingdom Grid',
    amount: 1845000,
    unit: 'kWh',
    ef: 0.207,
    efSource: 'DEFRA UK Grid 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 381.915,
    status: 'Approved',
  },

  // Scope 2: Purchased Heating & Steam
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Heating & Steam',
    name: 'District Steam (Natural Gas)',
    amount: 480000,
    unit: 'kWh',
    ef: 0.171,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 82.08,
    status: 'Approved',
  },

  // Scope 3: Purchased Goods
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Goods and Services',
    name: 'Aluminium ingot (India)',
    amount: 125000,
    unit: 'kg',
    ef: 8.92,
    efSource: 'Ecoinvent 3.9',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 1115.0,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Goods and Services',
    name: 'Corrugated Cardboard Packaging',
    amount: 45000,
    unit: 'kg',
    ef: 0.812,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 36.54,
    status: 'Approved',
  },

  // Scope 3: Capital Goods
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Capital Goods',
    name: 'Industrial Machinery & Equipment',
    amount: 350000,
    unit: 'USD',
    ef: 0.425,
    efSource: 'EXIOBASE v3.8',
    dateFrom: '15.02.2025',
    dateTo: '15.02.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 148.75,
    status: 'Approved',
  },

  // Scope 3: Upstream & Downstream Transportation
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Upstream Transportation',
    name: 'HGV Freight (Diesel, Laden)',
    amount: 840000,
    unit: 'ton.km',
    ef: 0.121,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 101.64,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Downstream Transportation',
    name: 'Container Sea Cargo Ship',
    amount: 4200000,
    unit: 'ton.km',
    ef: 0.016,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 67.2,
    status: 'Approved',
  },

  // Scope 3: Waste & Travel
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Waste Generated in Operations',
    name: 'Commercial Mixed Waste - Landfill',
    amount: 145,
    unit: 'tonne',
    ef: 446.2,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 64.699,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Business Travel',
    name: 'Long Haul Flight (Business Class)',
    amount: 320000,
    unit: 'passenger.km',
    ef: 0.254,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 81.28,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Employee Commuting',
    name: 'Average Diesel Passenger Car',
    amount: 480000,
    unit: 'km',
    ef: 0.171,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 82.08,
    status: 'Approved',
  },

  // Scope 3: End of Life
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'EOL Treatment of Sold Products',
    name: 'Metal (Mixed Can) - Closed Loop',
    amount: 85,
    unit: 'ton',
    ef: 6.411,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 544.935,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'EOL Treatment of Sold Products',
    name: 'Paper Board - Landfill Disposal',
    amount: 42,
    unit: 'ton',
    ef: 1164.489,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 48.908,
    status: 'Approved',
  },
];

export const SEED_FACILITIES: Partial<Facility>[] = [
  {
    organizationId: 1,
    name: 'WD Solutions Co. LLC',
    address: 'Full installation address, London',
    countryCode: 'UK',
    postCode: 'EC1A 1BB',
    unLocode: 'GB LON',
    isActive: true,
  },
  {
    organizationId: 1,
    name: 'Manchester Facility',
    address: '100 Industrial Estate, Manchester',
    countryCode: 'UK',
    postCode: 'M1 1AA',
    unLocode: 'GB MAN',
    isActive: true,
  },
];
