import { Service } from 'src/entities/service.entity';
import { ScopeCategoryMapping } from 'src/entities/scope-category-mapping.entity';
import { InventoryEntry } from 'src/entities/inventory-entry.entity';
import { Facility } from 'src/entities/facility.entity';

export const SEED_SERVICES: Partial<Service>[] = [
  {
    code: 'CARBON',
    name: 'CO2 Suite Carbon',
    description: 'Corporate Carbon Management and GHG Accounting Module',
    category: 'Carbon',
    tags: ['Carbon'],
    demoUrl: '/services/carbon',
    isActive: true,
  },
  {
    code: 'CBAM',
    name: 'CO2 Suite CBAM',
    description: 'EU Carbon Border Adjustment Mechanism Reporting Module',
    category: 'CBAM',
    tags: ['CBAM'],
    demoUrl: '/services/cbam',
    isActive: true,
  },
  {
    code: 'PEF_TEXTILES',
    name: 'CO2 Suite PEF',
    description:
      'EU Product Environmental Footprint Module for Textiles & Apparels',
    category: 'PEF',
    tags: ['PEF', 'Textiles & Apparels'],
    demoUrl: '/services/pef_textiles',
    isActive: true,
  },
  {
    code: 'LCA_PLASTICS',
    name: 'CO2 Suite LCA',
    description: 'Product Life Cycle Assessment for Plastic Manufacturing',
    category: 'LCA',
    tags: ['LCA', 'Plastics'],
    demoUrl: '/services/lca_plastics',
    isActive: true,
  },
  {
    code: 'LCA_METALS',
    name: 'CO2 Suite LCA',
    description: 'Product Life Cycle Assessment for Metal Manufacturing',
    category: 'LCA',
    tags: ['LCA', 'Metals'],
    demoUrl: '/services/lca_metals',
    isActive: true,
  },
  {
    code: 'ESG',
    name: 'CO2 Suite ESG',
    description:
      'Corporate Sustainability Management and CSRD Reporting Module',
    category: 'ESG',
    tags: ['ESG'],
    demoUrl: '/services/esg',
    isActive: true,
  },
  {
    code: 'EPD_CABLES',
    name: 'CO2 Suite EPD',
    description: 'Environmental Product Declarations Module for Cable Industry',
    category: 'EPD',
    tags: ['EPD', 'Cables'],
    demoUrl: '/services/epd_cables',
    isActive: true,
  },
];

export const SEED_SCOPE_CATEGORY_MAPPINGS: Partial<ScopeCategoryMapping>[] = [
  // Scope 1
  {
    scopeId: 1,
    categoryId: 1,
    description: 'Fuel burnt in stationary boilers, heaters, and generators',
    sortOrder: 1,
    isActive: true,
  },
  {
    scopeId: 1,
    categoryId: 2,
    description: 'Fuel burnt in company owned/leased vehicles and machinery',
    sortOrder: 2,
    isActive: true,
  },
  {
    scopeId: 1,
    categoryId: 3,
    description: 'Refrigerants, HVAC leaks, and gas escapes',
    sortOrder: 3,
    isActive: true,
  },
  {
    scopeId: 1,
    categoryId: 4,
    description: 'Emissions from chemical and physical manufacturing processes',
    sortOrder: 4,
    isActive: true,
  },

  // Scope 2
  {
    scopeId: 2,
    categoryId: 5,
    description: 'Grid electricity consumption across facility sites',
    sortOrder: 1,
    isActive: true,
  },
  {
    scopeId: 2,
    categoryId: 6,
    description: 'District heating, cooling, and industrial steam',
    sortOrder: 2,
    isActive: true,
  },

  // Scope 3
  {
    scopeId: 3,
    categoryId: 7,
    description: 'Upstream supply chain products, raw materials and services',
    sortOrder: 1,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 8,
    description: 'Capital equipment, IT hardware, and facility infrastructure',
    sortOrder: 2,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 9,
    description: 'WTT fuel extraction, refining and grid T&D losses',
    sortOrder: 3,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 10,
    description:
      'Inbound freight and logistics by 3rd party logistics providers',
    sortOrder: 4,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 11,
    description: 'Solid waste disposal, wastewater treatment and recycling',
    sortOrder: 5,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 12,
    description: 'Commercial flights, train travel, taxis, and hotel stays',
    sortOrder: 6,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 13,
    description: 'Staff commuting between primary residence and workplace',
    sortOrder: 7,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 14,
    description: 'Outbound logistics and distribution of sold products',
    sortOrder: 8,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 15,
    description: 'Processing of intermediate goods sold to 3rd parties',
    sortOrder: 9,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 16,
    description: 'Direct energy and emissions during product use phase',
    sortOrder: 10,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 17,
    description: 'End of life disposal, landfilling, and recycling of products',
    sortOrder: 11,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 18,
    description: 'Emissions from independent franchise operations',
    sortOrder: 12,
    isActive: true,
  },
  {
    scopeId: 3,
    categoryId: 19,
    description: 'Financed emissions and corporate equity investments',
    sortOrder: 13,
    isActive: true,
  },
];



export const SEED_INVENTORY_ENTRIES: Partial<InventoryEntry>[] = [
  // Scope 1: Stationary Combustion
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Stationary Combustion',
    name: 'Natural Gas',
    amount: 54200,
    unit: 'sm3',
    ef: 1.942,
    efSource: 'IPCC (Commercial Use)-AR6',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 105.256,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Stationary Combustion',
    name: 'Diesel Fuel',
    amount: 18500,
    unit: 'L',
    ef: 2.684,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 49.654,
    status: 'Approved',
  },

  // Scope 1: Mobile Combustion & Fugitives
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Mobile Combustion',
    name: 'Diesel - On Road Fleet',
    amount: 12400,
    unit: 'L',
    ef: 2.666,
    efSource: 'IPCC-AR6',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 33.058,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Fugitive Emissions',
    name: 'Refrigerant R-134a',
    amount: 28,
    unit: 'kg',
    ef: 1530.0,
    efSource: 'IPCC-AR6 GWP',
    dateFrom: '15.03.2025',
    dateTo: '15.03.2025',
    facility: 'Manchester Facility',
    emission: 42.84,
    status: 'Approved',
  },

  // Scope 2: Purchased Electricity
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Electricity',
    name: 'Republic of Türkiye',
    amount: 32644678,
    unit: 'kWh',
    ef: 0.442,
    efSource: 'IEA Grid Factors 2023',
    dateFrom: '01.01.2024',
    dateTo: '31.12.2024',
    facility: 'WD Solutions Co. LLC',
    emission: 14428.948,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Electricity',
    name: 'United Kingdom Grid',
    amount: 1845000,
    unit: 'kWh',
    ef: 0.207,
    efSource: 'DEFRA UK Grid 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 381.915,
    status: 'Approved',
  },

  // Scope 2: Purchased Heating & Steam
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Heating & Steam',
    name: 'District Steam (Natural Gas)',
    amount: 480000,
    unit: 'kWh',
    ef: 0.171,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 82.08,
    status: 'Approved',
  },

  // Scope 3: Purchased Goods
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Goods and Services',
    name: 'Aluminium ingot (India)',
    amount: 125000,
    unit: 'kg',
    ef: 8.92,
    efSource: 'Ecoinvent 3.9',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 1115.0,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Purchased Goods and Services',
    name: 'Corrugated Cardboard Packaging',
    amount: 45000,
    unit: 'kg',
    ef: 0.812,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 36.54,
    status: 'Approved',
  },

  // Scope 3: Capital Goods
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Capital Goods',
    name: 'Industrial Machinery & Equipment',
    amount: 350000,
    unit: 'USD',
    ef: 0.425,
    efSource: 'EXIOBASE v3.8',
    dateFrom: '15.02.2025',
    dateTo: '15.02.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 148.75,
    status: 'Approved',
  },

  // Scope 3: Upstream & Downstream Transportation
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Upstream Transportation',
    name: 'HGV Freight (Diesel, Laden)',
    amount: 840000,
    unit: 'ton.km',
    ef: 0.121,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 101.64,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Downstream Transportation',
    name: 'Container Sea Cargo Ship',
    amount: 4200000,
    unit: 'ton.km',
    ef: 0.016,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 67.2,
    status: 'Approved',
  },

  // Scope 3: Waste & Travel
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Waste Generated in Operations',
    name: 'Commercial Mixed Waste - Landfill',
    amount: 145,
    unit: 'tonne',
    ef: 446.2,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 64.699,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Business Travel',
    name: 'Long Haul Flight (Business Class)',
    amount: 320000,
    unit: 'passenger.km',
    ef: 0.254,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 81.28,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'Employee Commuting',
    name: 'Average Diesel Passenger Car',
    amount: 480000,
    unit: 'km',
    ef: 0.171,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 82.08,
    status: 'Approved',
  },

  // Scope 3: End of Life
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'EOL Treatment of Sold Products',
    name: 'Metal (Mixed Can) - Closed Loop',
    amount: 85,
    unit: 'ton',
    ef: 6.411,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'WD Solutions Co. LLC',
    emission: 544.935,
    status: 'Approved',
  },
  {
    organizationId: 1,
    serviceCode: 'CARBON',
    category: 'EOL Treatment of Sold Products',
    name: 'Paper Board - Landfill Disposal',
    amount: 42,
    unit: 'ton',
    ef: 1164.489,
    efSource: 'DEFRA 2024',
    dateFrom: '01.01.2025',
    dateTo: '31.12.2025',
    facility: 'Manchester Facility',
    emission: 48.908,
    status: 'Approved',
  },
];

export const SEED_FACILITIES: Partial<Facility>[] = [
  {
    organizationId: 1,
    name: 'WD Solutions Co. LLC',
    address: 'Full installation address, London',
    countryCode: 'UK',
    postCode: 'EC1A 1BB',
    unLocode: 'GB LON',
    isActive: true,
  },
  {
    organizationId: 1,
    name: 'Manchester Facility',
    address: '100 Industrial Estate, Manchester',
    countryCode: 'UK',
    postCode: 'M1 1AA',
    unLocode: 'GB MAN',
    isActive: true,
  },
];
