/**
 * Enterprise Permission Catalog (ADR: RBAC Fine-Grained Governance)
 *
 * Explicit resource-action permission tokens matching enterprise authorization.
 */
export enum Permission {
  // Master Management
  MASTER_ITEM_CREATE = 'MASTER_ITEM.CREATE',
  MASTER_ITEM_READ = 'MASTER_ITEM.READ',
  MASTER_ITEM_UPDATE = 'MASTER_ITEM.UPDATE',
  MASTER_ITEM_DELETE = 'MASTER_ITEM.DELETE',
  MASTER_ITEM_PUBLISH = 'MASTER_ITEM.PUBLISH',

  // Emission Factors
  EMISSION_FACTOR_CREATE = 'EMISSION_FACTOR.CREATE',
  EMISSION_FACTOR_READ = 'EMISSION_FACTOR.READ',
  EMISSION_FACTOR_UPDATE = 'EMISSION_FACTOR.UPDATE',
  EMISSION_FACTOR_APPROVE = 'EMISSION_FACTOR.APPROVE',
  EMISSION_FACTOR_DELETE = 'EMISSION_FACTOR.DELETE',

  // Formula & Governance
  FORMULA_CREATE = 'FORMULA.CREATE',
  FORMULA_EDIT = 'FORMULA.EDIT',
  FORMULA_APPROVE = 'FORMULA.APPROVE',

  // Operations & Inventory
  INVENTORY_CREATE = 'INVENTORY.CREATE',
  INVENTORY_SUBMIT = 'INVENTORY.SUBMIT',
  INVENTORY_APPROVE = 'INVENTORY.APPROVE',
  INVENTORY_DELETE = 'INVENTORY.DELETE',

  // Calculations & Reporting
  CALCULATION_RUN = 'CALCULATION.RUN',
  REPORT_GENERATE = 'REPORT.GENERATE',
  REPORT_EXPORT = 'REPORT.EXPORT',
  AUDIT_LOG_READ = 'AUDIT_LOG.READ',
}

export type PermissionString = `${Permission}`;
